/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package worldcupapp;

/**
 *
 * @author Nathan Ryan x13448212 Group 7
 */
public class GroupB extends javax.swing.JFrame {

    /**
     * Creates new form GroupB
     */
    public GroupB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        v6 = new javax.swing.JLabel();
        fixture6 = new javax.swing.JPanel();
        venue6 = new javax.swing.JLabel();
        date6 = new javax.swing.JLabel();
        holland3Lbl = new javax.swing.JLabel();
        chile3Lbl = new javax.swing.JLabel();
        hollandFlag = new javax.swing.JLabel();
        chileFlag = new javax.swing.JLabel();
        spain3Lbl = new javax.swing.JLabel();
        v5 = new javax.swing.JLabel();
        oz3Lbl = new javax.swing.JLabel();
        fixture5 = new javax.swing.JPanel();
        venue5 = new javax.swing.JLabel();
        date5 = new javax.swing.JLabel();
        ozFlag = new javax.swing.JLabel();
        v4 = new javax.swing.JLabel();
        fixture4 = new javax.swing.JPanel();
        venue4 = new javax.swing.JLabel();
        date4 = new javax.swing.JLabel();
        oz2Lbl = new javax.swing.JLabel();
        holland2Lbl = new javax.swing.JLabel();
        ozFlag1 = new javax.swing.JLabel();
        spainFlag1 = new javax.swing.JLabel();
        hollandFlag1 = new javax.swing.JLabel();
        spain2Lbl = new javax.swing.JLabel();
        v3 = new javax.swing.JLabel();
        fixture3 = new javax.swing.JPanel();
        venue3 = new javax.swing.JLabel();
        date3 = new javax.swing.JLabel();
        chile2Lbl = new javax.swing.JLabel();
        chileFlag1 = new javax.swing.JLabel();
        spainFlag2 = new javax.swing.JLabel();
        chileLbl = new javax.swing.JLabel();
        v2 = new javax.swing.JLabel();
        fixture2 = new javax.swing.JPanel();
        venue2 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        ozLbl = new javax.swing.JLabel();
        chileFlag2 = new javax.swing.JLabel();
        ozFlag2 = new javax.swing.JLabel();
        v1 = new javax.swing.JLabel();
        fixture1 = new javax.swing.JPanel();
        venue1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        spainLbl = new javax.swing.JLabel();
        hollandLbl = new javax.swing.JLabel();
        spainFlag3 = new javax.swing.JLabel();
        hollandFlag2 = new javax.swing.JLabel();
        groupALbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        taskbar = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        jLabel12.setText("v");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Team B");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Team A");

        jPanel4.setForeground(new java.awt.Color(255, 255, 102));

        jLabel15.setText("Date");

        jLabel16.setText("Venue");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        v6.setText("v");
        jLayeredPane1.add(v6);
        v6.setBounds(160, 560, 6, 14);

        fixture6.setBackground(new java.awt.Color(255, 255, 0));

        venue6.setText("Sao Paulo");

        date6.setText("23/06 13:00");

        javax.swing.GroupLayout fixture6Layout = new javax.swing.GroupLayout(fixture6);
        fixture6.setLayout(fixture6Layout);
        fixture6Layout.setHorizontalGroup(
            fixture6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(venue6)
                .addContainerGap())
        );
        fixture6Layout.setVerticalGroup(
            fixture6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue6)
                    .addComponent(date6)))
        );

        jLayeredPane1.add(fixture6);
        fixture6.setBounds(20, 530, 300, 14);

        holland3Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        holland3Lbl.setText("Netherlands");
        jLayeredPane1.add(holland3Lbl);
        holland3Lbl.setBounds(20, 590, 72, 17);

        chile3Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chile3Lbl.setText("Chile");
        jLayeredPane1.add(chile3Lbl);
        chile3Lbl.setBounds(260, 590, 28, 17);

        hollandFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Netherlands.png"))); // NOI18N
        hollandFlag.setText("jLabel1");
        jLayeredPane1.add(hollandFlag);
        hollandFlag.setBounds(250, 390, 65, 40);

        chileFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Chile.png"))); // NOI18N
        chileFlag.setText("jLabel2");
        jLayeredPane1.add(chileFlag);
        chileFlag.setBounds(20, 220, 65, 40);

        spain3Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spain3Lbl.setText("Spain");
        jLayeredPane1.add(spain3Lbl);
        spain3Lbl.setBounds(260, 510, 33, 17);

        v5.setText("v");
        jLayeredPane1.add(v5);
        v5.setBounds(160, 470, 6, 14);

        oz3Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oz3Lbl.setText("Australia");
        jLayeredPane1.add(oz3Lbl);
        oz3Lbl.setBounds(20, 510, 50, 17);

        fixture5.setBackground(new java.awt.Color(255, 255, 0));

        venue5.setText("Curitiba");

        date5.setText("23/06 13:00");

        javax.swing.GroupLayout fixture5Layout = new javax.swing.GroupLayout(fixture5);
        fixture5.setLayout(fixture5Layout);
        fixture5Layout.setHorizontalGroup(
            fixture5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(venue5)
                .addContainerGap())
        );
        fixture5Layout.setVerticalGroup(
            fixture5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue5)
                    .addComponent(date5)))
        );

        jLayeredPane1.add(fixture5);
        fixture5.setBounds(20, 450, 300, 14);

        ozFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Australia.png"))); // NOI18N
        ozFlag.setText("jLabel1");
        jLayeredPane1.add(ozFlag);
        ozFlag.setBounds(250, 220, 65, 40);

        v4.setText("v");
        jLayeredPane1.add(v4);
        v4.setBounds(160, 400, 6, 14);

        fixture4.setBackground(new java.awt.Color(255, 255, 0));

        venue4.setText("Porto Alegre");

        date4.setText("18/06 13:00");

        javax.swing.GroupLayout fixture4Layout = new javax.swing.GroupLayout(fixture4);
        fixture4.setLayout(fixture4Layout);
        fixture4Layout.setHorizontalGroup(
            fixture4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(venue4)
                .addContainerGap())
        );
        fixture4Layout.setVerticalGroup(
            fixture4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue4)
                    .addComponent(date4)))
        );

        jLayeredPane1.add(fixture4);
        fixture4.setBounds(20, 370, 300, 14);

        oz2Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oz2Lbl.setText("Australia");
        jLayeredPane1.add(oz2Lbl);
        oz2Lbl.setBounds(20, 430, 50, 17);

        holland2Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        holland2Lbl.setText("Netherlands");
        jLayeredPane1.add(holland2Lbl);
        holland2Lbl.setBounds(250, 430, 72, 17);

        ozFlag1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Australia.png"))); // NOI18N
        ozFlag1.setText("jLabel1");
        jLayeredPane1.add(ozFlag1);
        ozFlag1.setBounds(20, 470, 65, 40);

        spainFlag1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Spain.png"))); // NOI18N
        spainFlag1.setText("jLabel2");
        jLayeredPane1.add(spainFlag1);
        spainFlag1.setBounds(20, 130, 65, 40);

        hollandFlag1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Netherlands.png"))); // NOI18N
        hollandFlag1.setText("jLabel1");
        jLayeredPane1.add(hollandFlag1);
        hollandFlag1.setBounds(250, 130, 65, 40);

        spain2Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spain2Lbl.setText("Spain");
        jLayeredPane1.add(spain2Lbl);
        spain2Lbl.setBounds(30, 350, 33, 17);

        v3.setText("v");
        jLayeredPane1.add(v3);
        v3.setBounds(160, 340, 6, 14);

        fixture3.setBackground(new java.awt.Color(255, 255, 0));

        venue3.setText("Rio De Janeiro ");

        date3.setText("18/06 16:00");

        javax.swing.GroupLayout fixture3Layout = new javax.swing.GroupLayout(fixture3);
        fixture3.setLayout(fixture3Layout);
        fixture3Layout.setHorizontalGroup(
            fixture3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(venue3)
                .addContainerGap())
        );
        fixture3Layout.setVerticalGroup(
            fixture3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue3)
                    .addComponent(date3)))
        );

        jLayeredPane1.add(fixture3);
        fixture3.setBounds(20, 290, 300, 14);

        chile2Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chile2Lbl.setText("Chile");
        jLayeredPane1.add(chile2Lbl);
        chile2Lbl.setBounds(260, 350, 28, 17);

        chileFlag1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Chile.png"))); // NOI18N
        chileFlag1.setText("jLabel2");
        jLayeredPane1.add(chileFlag1);
        chileFlag1.setBounds(250, 550, 65, 40);

        spainFlag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Spain.png"))); // NOI18N
        spainFlag2.setText("jLabel2");
        jLayeredPane1.add(spainFlag2);
        spainFlag2.setBounds(250, 470, 65, 40);

        chileLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chileLbl.setText("Chile");
        jLayeredPane1.add(chileLbl);
        chileLbl.setBounds(30, 260, 28, 17);

        v2.setText("v");
        jLayeredPane1.add(v2);
        v2.setBounds(160, 260, 6, 14);

        fixture2.setBackground(new java.awt.Color(255, 255, 0));

        venue2.setText("Cuiaba");

        date2.setText("13/06 18:00");

        javax.swing.GroupLayout fixture2Layout = new javax.swing.GroupLayout(fixture2);
        fixture2.setLayout(fixture2Layout);
        fixture2Layout.setHorizontalGroup(
            fixture2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(date2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(venue2)
                .addContainerGap())
        );
        fixture2Layout.setVerticalGroup(
            fixture2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue2)
                    .addComponent(date2)))
        );

        jLayeredPane1.add(fixture2);
        fixture2.setBounds(20, 200, 300, 14);

        ozLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ozLbl.setText("Australia");
        jLayeredPane1.add(ozLbl);
        ozLbl.setBounds(250, 260, 50, 17);

        chileFlag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Chile.png"))); // NOI18N
        chileFlag2.setText("jLabel2");
        jLayeredPane1.add(chileFlag2);
        chileFlag2.setBounds(250, 310, 65, 40);

        ozFlag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Australia.png"))); // NOI18N
        ozFlag2.setText("jLabel1");
        jLayeredPane1.add(ozFlag2);
        ozFlag2.setBounds(20, 390, 65, 40);

        v1.setText("v");
        jLayeredPane1.add(v1);
        v1.setBounds(160, 170, 6, 14);

        fixture1.setBackground(new java.awt.Color(255, 255, 0));

        venue1.setText("Salvador");

        date1.setText("13/06 16:00");

        javax.swing.GroupLayout fixture1Layout = new javax.swing.GroupLayout(fixture1);
        fixture1.setLayout(fixture1Layout);
        fixture1Layout.setHorizontalGroup(
            fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(date1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(venue1)
                .addContainerGap())
        );
        fixture1Layout.setVerticalGroup(
            fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue1)
                    .addComponent(date1)))
        );

        jLayeredPane1.add(fixture1);
        fixture1.setBounds(20, 110, 300, 14);

        spainLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spainLbl.setText("Spain");
        jLayeredPane1.add(spainLbl);
        spainLbl.setBounds(30, 170, 33, 17);

        hollandLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hollandLbl.setText("Netherlands");
        jLayeredPane1.add(hollandLbl);
        hollandLbl.setBounds(250, 170, 72, 17);

        spainFlag3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Spain.png"))); // NOI18N
        spainFlag3.setText("jLabel2");
        jLayeredPane1.add(spainFlag3);
        spainFlag3.setBounds(20, 310, 65, 40);

        hollandFlag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Netherlands.png"))); // NOI18N
        hollandFlag2.setText("jLabel1");
        jLayeredPane1.add(hollandFlag2);
        hollandFlag2.setBounds(20, 550, 65, 40);

        groupALbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        groupALbl.setForeground(new java.awt.Color(255, 255, 255));
        groupALbl.setText("Group B");
        jLayeredPane1.add(groupALbl);
        groupALbl.setBounds(120, 60, 100, 50);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fixtures/back.png"))); // NOI18N
        backBtn.setOpaque(false);
        backBtn.setOpaque(false);
        backBtn.setContentAreaFilled( false );
        backBtn.setBorder( null );
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(backBtn);
        backBtn.setBounds(10, 10, 80, 50);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fixtures/home.png"))); // NOI18N
        homeBtn.setOpaque(false);
        homeBtn.setOpaque(false);
        homeBtn.setContentAreaFilled( false );
        homeBtn.setBorder( null );
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(homeBtn);
        homeBtn.setBounds(270, 10, 70, 50);

        taskbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Taskbar.png"))); // NOI18N
        taskbar.setText("jLabel2");
        jLayeredPane1.add(taskbar);
        taskbar.setBounds(0, -10, 360, 140);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        jLayeredPane1.add(bg);
        bg.setBounds(0, 0, 360, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        GroupFixtures gf = new GroupFixtures();
        gf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomeScreen h = new HomeScreen();
        h.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupB().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel chile2Lbl;
    private javax.swing.JLabel chile3Lbl;
    private javax.swing.JLabel chileFlag;
    private javax.swing.JLabel chileFlag1;
    private javax.swing.JLabel chileFlag2;
    private javax.swing.JLabel chileLbl;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel date3;
    private javax.swing.JLabel date4;
    private javax.swing.JLabel date5;
    private javax.swing.JLabel date6;
    private javax.swing.JPanel fixture1;
    private javax.swing.JPanel fixture2;
    private javax.swing.JPanel fixture3;
    private javax.swing.JPanel fixture4;
    private javax.swing.JPanel fixture5;
    private javax.swing.JPanel fixture6;
    private javax.swing.JLabel groupALbl;
    private javax.swing.JLabel holland2Lbl;
    private javax.swing.JLabel holland3Lbl;
    private javax.swing.JLabel hollandFlag;
    private javax.swing.JLabel hollandFlag1;
    private javax.swing.JLabel hollandFlag2;
    private javax.swing.JLabel hollandLbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel oz2Lbl;
    private javax.swing.JLabel oz3Lbl;
    private javax.swing.JLabel ozFlag;
    private javax.swing.JLabel ozFlag1;
    private javax.swing.JLabel ozFlag2;
    private javax.swing.JLabel ozLbl;
    private javax.swing.JLabel spain2Lbl;
    private javax.swing.JLabel spain3Lbl;
    private javax.swing.JLabel spainFlag1;
    private javax.swing.JLabel spainFlag2;
    private javax.swing.JLabel spainFlag3;
    private javax.swing.JLabel spainLbl;
    private javax.swing.JLabel taskbar;
    private javax.swing.JLabel v1;
    private javax.swing.JLabel v2;
    private javax.swing.JLabel v3;
    private javax.swing.JLabel v4;
    private javax.swing.JLabel v5;
    private javax.swing.JLabel v6;
    private javax.swing.JLabel venue1;
    private javax.swing.JLabel venue2;
    private javax.swing.JLabel venue3;
    private javax.swing.JLabel venue4;
    private javax.swing.JLabel venue5;
    private javax.swing.JLabel venue6;
    // End of variables declaration//GEN-END:variables
}
