/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package worldcupapp;

/**
 *
 * @author Nathan Ryan x13448212 Group 7
 */
public class GroupD extends javax.swing.JFrame {

    /**
     * Creates new form GroupD
     */
    public GroupD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        v6 = new javax.swing.JLabel();
        fixture8 = new javax.swing.JPanel();
        venue8 = new javax.swing.JLabel();
        date8 = new javax.swing.JLabel();
        costaLbl3 = new javax.swing.JLabel();
        engLbl3 = new javax.swing.JLabel();
        costaFlag2 = new javax.swing.JLabel();
        englandFlag = new javax.swing.JLabel();
        uruLbl3 = new javax.swing.JLabel();
        v5 = new javax.swing.JLabel();
        italyLbl3 = new javax.swing.JLabel();
        fixture5 = new javax.swing.JPanel();
        venue5 = new javax.swing.JLabel();
        date5 = new javax.swing.JLabel();
        italyFlag = new javax.swing.JLabel();
        v4 = new javax.swing.JLabel();
        fixture4 = new javax.swing.JPanel();
        venue4 = new javax.swing.JLabel();
        date4 = new javax.swing.JLabel();
        italyLbl2 = new javax.swing.JLabel();
        costaLbl2 = new javax.swing.JLabel();
        italyFlag3 = new javax.swing.JLabel();
        uruFlag = new javax.swing.JLabel();
        costaFlag = new javax.swing.JLabel();
        uruLbl2 = new javax.swing.JLabel();
        v3 = new javax.swing.JLabel();
        fixture3 = new javax.swing.JPanel();
        venue3 = new javax.swing.JLabel();
        date3 = new javax.swing.JLabel();
        englLbl2 = new javax.swing.JLabel();
        englandFlag3 = new javax.swing.JLabel();
        uruFlag3 = new javax.swing.JLabel();
        engLbl = new javax.swing.JLabel();
        v2 = new javax.swing.JLabel();
        fixture2 = new javax.swing.JPanel();
        venue2 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        italyLbl = new javax.swing.JLabel();
        englandFlag2 = new javax.swing.JLabel();
        italyFlag2 = new javax.swing.JLabel();
        v1 = new javax.swing.JLabel();
        fixture1 = new javax.swing.JPanel();
        venue1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        uruLbl = new javax.swing.JLabel();
        costaLbl = new javax.swing.JLabel();
        uruFlag2 = new javax.swing.JLabel();
        costaFlag3 = new javax.swing.JLabel();
        groupDLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        taskbar = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        v6.setText("v");
        jLayeredPane1.add(v6);
        v6.setBounds(160, 560, 6, 14);

        fixture8.setBackground(new java.awt.Color(255, 255, 0));

        venue8.setText("Belo Horizonte");

        date8.setText("24/06 13:00");

        javax.swing.GroupLayout fixture8Layout = new javax.swing.GroupLayout(fixture8);
        fixture8.setLayout(fixture8Layout);
        fixture8Layout.setHorizontalGroup(
            fixture8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(venue8)
                .addContainerGap())
        );
        fixture8Layout.setVerticalGroup(
            fixture8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue8)
                    .addComponent(date8)))
        );

        jLayeredPane1.add(fixture8);
        fixture8.setBounds(20, 530, 300, 14);

        costaLbl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        costaLbl3.setText("Costa Rica");
        jLayeredPane1.add(costaLbl3);
        costaLbl3.setBounds(20, 590, 70, 17);

        engLbl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        engLbl3.setText("England");
        jLayeredPane1.add(engLbl3);
        engLbl3.setBounds(250, 590, 80, 17);

        costaFlag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Costa-Rica.png"))); // NOI18N
        costaFlag2.setText("jLabel1");
        jLayeredPane1.add(costaFlag2);
        costaFlag2.setBounds(250, 390, 65, 40);

        englandFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/England.png"))); // NOI18N
        englandFlag.setText("jLabel2");
        jLayeredPane1.add(englandFlag);
        englandFlag.setBounds(20, 220, 65, 40);

        uruLbl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uruLbl3.setText("Uruguay");
        jLayeredPane1.add(uruLbl3);
        uruLbl3.setBounds(250, 510, 60, 17);

        v5.setText("v");
        jLayeredPane1.add(v5);
        v5.setBounds(160, 470, 6, 14);

        italyLbl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        italyLbl3.setText("Italy");
        jLayeredPane1.add(italyLbl3);
        italyLbl3.setBounds(20, 510, 26, 17);

        fixture5.setBackground(new java.awt.Color(255, 255, 0));

        venue5.setText("Natal");

        date5.setText("24/06 13:00");

        javax.swing.GroupLayout fixture5Layout = new javax.swing.GroupLayout(fixture5);
        fixture5.setLayout(fixture5Layout);
        fixture5Layout.setHorizontalGroup(
            fixture5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(venue5)
                .addContainerGap())
        );
        fixture5Layout.setVerticalGroup(
            fixture5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue5)
                    .addComponent(date5)))
        );

        jLayeredPane1.add(fixture5);
        fixture5.setBounds(20, 450, 300, 14);

        italyFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Italy.png"))); // NOI18N
        italyFlag.setText("jLabel1");
        jLayeredPane1.add(italyFlag);
        italyFlag.setBounds(250, 220, 65, 40);

        v4.setText("v");
        jLayeredPane1.add(v4);
        v4.setBounds(160, 400, 6, 14);

        fixture4.setBackground(new java.awt.Color(255, 255, 0));

        venue4.setText("Recife");

        date4.setText("20/06 16:00");

        javax.swing.GroupLayout fixture4Layout = new javax.swing.GroupLayout(fixture4);
        fixture4.setLayout(fixture4Layout);
        fixture4Layout.setHorizontalGroup(
            fixture4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(venue4)
                .addContainerGap())
        );
        fixture4Layout.setVerticalGroup(
            fixture4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue4)
                    .addComponent(date4)))
        );

        jLayeredPane1.add(fixture4);
        fixture4.setBounds(20, 370, 300, 14);

        italyLbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        italyLbl2.setText("Italy");
        jLayeredPane1.add(italyLbl2);
        italyLbl2.setBounds(20, 430, 26, 17);

        costaLbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        costaLbl2.setText("Costa Rica");
        jLayeredPane1.add(costaLbl2);
        costaLbl2.setBounds(250, 430, 70, 17);

        italyFlag3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Italy.png"))); // NOI18N
        italyFlag3.setText("jLabel1");
        jLayeredPane1.add(italyFlag3);
        italyFlag3.setBounds(20, 470, 65, 40);

        uruFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Uruguay.png"))); // NOI18N
        uruFlag.setText("jLabel2");
        jLayeredPane1.add(uruFlag);
        uruFlag.setBounds(20, 130, 65, 40);

        costaFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Costa-Rica.png"))); // NOI18N
        costaFlag.setText("jLabel1");
        jLayeredPane1.add(costaFlag);
        costaFlag.setBounds(250, 130, 65, 40);

        uruLbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uruLbl2.setText("Uruguay");
        jLayeredPane1.add(uruLbl2);
        uruLbl2.setBounds(30, 350, 60, 17);

        v3.setText("v");
        jLayeredPane1.add(v3);
        v3.setBounds(160, 340, 6, 14);

        fixture3.setBackground(new java.awt.Color(255, 255, 0));

        venue3.setText("Sao Paulo");

        date3.setText("19/06 16:00");

        javax.swing.GroupLayout fixture3Layout = new javax.swing.GroupLayout(fixture3);
        fixture3.setLayout(fixture3Layout);
        fixture3Layout.setHorizontalGroup(
            fixture3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(venue3)
                .addContainerGap())
        );
        fixture3Layout.setVerticalGroup(
            fixture3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue3)
                    .addComponent(date3)))
        );

        jLayeredPane1.add(fixture3);
        fixture3.setBounds(20, 290, 300, 14);

        englLbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        englLbl2.setText("England");
        jLayeredPane1.add(englLbl2);
        englLbl2.setBounds(250, 350, 80, 17);

        englandFlag3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/England.png"))); // NOI18N
        englandFlag3.setText("jLabel2");
        jLayeredPane1.add(englandFlag3);
        englandFlag3.setBounds(250, 550, 65, 40);

        uruFlag3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Uruguay.png"))); // NOI18N
        uruFlag3.setText("jLabel2");
        jLayeredPane1.add(uruFlag3);
        uruFlag3.setBounds(250, 470, 65, 40);

        engLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        engLbl.setText("England");
        jLayeredPane1.add(engLbl);
        engLbl.setBounds(20, 260, 80, 17);

        v2.setText("v");
        jLayeredPane1.add(v2);
        v2.setBounds(160, 260, 6, 14);

        fixture2.setBackground(new java.awt.Color(255, 255, 0));

        venue2.setText("Manaus");

        date2.setText("14/06 18:00");

        javax.swing.GroupLayout fixture2Layout = new javax.swing.GroupLayout(fixture2);
        fixture2.setLayout(fixture2Layout);
        fixture2Layout.setHorizontalGroup(
            fixture2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(date2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(venue2)
                .addContainerGap())
        );
        fixture2Layout.setVerticalGroup(
            fixture2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue2)
                    .addComponent(date2)))
        );

        jLayeredPane1.add(fixture2);
        fixture2.setBounds(20, 200, 300, 14);

        italyLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        italyLbl.setText("Italy");
        jLayeredPane1.add(italyLbl);
        italyLbl.setBounds(250, 260, 26, 17);

        englandFlag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/England.png"))); // NOI18N
        englandFlag2.setText("jLabel2");
        jLayeredPane1.add(englandFlag2);
        englandFlag2.setBounds(250, 310, 65, 40);

        italyFlag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Italy.png"))); // NOI18N
        italyFlag2.setText("jLabel1");
        jLayeredPane1.add(italyFlag2);
        italyFlag2.setBounds(20, 390, 65, 40);

        v1.setText("v");
        jLayeredPane1.add(v1);
        v1.setBounds(160, 170, 6, 14);

        fixture1.setBackground(new java.awt.Color(255, 255, 0));

        venue1.setText("Fortaleza");

        date1.setText("14/06 16:00");

        javax.swing.GroupLayout fixture1Layout = new javax.swing.GroupLayout(fixture1);
        fixture1.setLayout(fixture1Layout);
        fixture1Layout.setHorizontalGroup(
            fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(date1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(venue1)
                .addContainerGap())
        );
        fixture1Layout.setVerticalGroup(
            fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue1)
                    .addComponent(date1)))
        );

        jLayeredPane1.add(fixture1);
        fixture1.setBounds(20, 110, 300, 14);

        uruLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uruLbl.setText("Uruguay");
        jLayeredPane1.add(uruLbl);
        uruLbl.setBounds(20, 170, 60, 17);

        costaLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        costaLbl.setText("Costa Rica");
        jLayeredPane1.add(costaLbl);
        costaLbl.setBounds(250, 170, 70, 17);

        uruFlag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Uruguay.png"))); // NOI18N
        uruFlag2.setText("jLabel2");
        jLayeredPane1.add(uruFlag2);
        uruFlag2.setBounds(20, 310, 65, 40);

        costaFlag3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Costa-Rica.png"))); // NOI18N
        costaFlag3.setText("jLabel1");
        jLayeredPane1.add(costaFlag3);
        costaFlag3.setBounds(20, 550, 65, 40);

        groupDLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        groupDLbl.setForeground(new java.awt.Color(255, 255, 255));
        groupDLbl.setText("Group D");
        jLayeredPane1.add(groupDLbl);
        groupDLbl.setBounds(120, 60, 100, 50);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fixtures/back.png"))); // NOI18N
        backBtn.setOpaque(false);
        backBtn.setOpaque(false);
        backBtn.setContentAreaFilled( false );
        backBtn.setBorder( null );
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(backBtn);
        backBtn.setBounds(10, 10, 80, 50);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fixtures/home.png"))); // NOI18N
        homeBtn.setOpaque(false);
        homeBtn.setOpaque(false);
        homeBtn.setContentAreaFilled( false );
        homeBtn.setBorder( null );
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(homeBtn);
        homeBtn.setBounds(270, 10, 70, 50);

        taskbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Taskbar.png"))); // NOI18N
        taskbar.setText("jLabel2");
        jLayeredPane1.add(taskbar);
        taskbar.setBounds(0, -10, 360, 140);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        jLayeredPane1.add(bg);
        bg.setBounds(0, 0, 360, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        GroupFixtures gf = new GroupFixtures();
        gf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomeScreen h = new HomeScreen();
        h.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* SettitleLblbus look and feel */
        //<editor-fold defaultstate="collatitleLblsc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupD().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel costaFlag;
    private javax.swing.JLabel costaFlag2;
    private javax.swing.JLabel costaFlag3;
    private javax.swing.JLabel costaLbl;
    private javax.swing.JLabel costaLbl2;
    private javax.swing.JLabel costaLbl3;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel date3;
    private javax.swing.JLabel date4;
    private javax.swing.JLabel date5;
    private javax.swing.JLabel date8;
    private javax.swing.JLabel engLbl;
    private javax.swing.JLabel engLbl3;
    private javax.swing.JLabel englLbl2;
    private javax.swing.JLabel englandFlag;
    private javax.swing.JLabel englandFlag2;
    private javax.swing.JLabel englandFlag3;
    private javax.swing.JPanel fixture1;
    private javax.swing.JPanel fixture2;
    private javax.swing.JPanel fixture3;
    private javax.swing.JPanel fixture4;
    private javax.swing.JPanel fixture5;
    private javax.swing.JPanel fixture8;
    private javax.swing.JLabel groupDLbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel italyFlag;
    private javax.swing.JLabel italyFlag2;
    private javax.swing.JLabel italyFlag3;
    private javax.swing.JLabel italyLbl;
    private javax.swing.JLabel italyLbl2;
    private javax.swing.JLabel italyLbl3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel taskbar;
    private javax.swing.JLabel uruFlag;
    private javax.swing.JLabel uruFlag2;
    private javax.swing.JLabel uruFlag3;
    private javax.swing.JLabel uruLbl;
    private javax.swing.JLabel uruLbl2;
    private javax.swing.JLabel uruLbl3;
    private javax.swing.JLabel v1;
    private javax.swing.JLabel v2;
    private javax.swing.JLabel v3;
    private javax.swing.JLabel v4;
    private javax.swing.JLabel v5;
    private javax.swing.JLabel v6;
    private javax.swing.JLabel venue1;
    private javax.swing.JLabel venue2;
    private javax.swing.JLabel venue3;
    private javax.swing.JLabel venue4;
    private javax.swing.JLabel venue5;
    private javax.swing.JLabel venue8;
    // End of variables declaration//GEN-END:variables
}
