/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package worldcupapp;

/**
 *
 * @author Nathan Ryan x13448212 Group 7
 */
public class GroupA extends javax.swing.JFrame {

    /**
     * Creates new form GroupA
     */
    public GroupA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        v6 = new javax.swing.JLabel();
        fixture6 = new javax.swing.JPanel();
        venue6 = new javax.swing.JLabel();
        date6 = new javax.swing.JLabel();
        croLbl3 = new javax.swing.JLabel();
        mexLbl3 = new javax.swing.JLabel();
        croFlag2 = new javax.swing.JLabel();
        mexFlag = new javax.swing.JLabel();
        braLbl3 = new javax.swing.JLabel();
        v5 = new javax.swing.JLabel();
        camLbl3 = new javax.swing.JLabel();
        fixture5 = new javax.swing.JPanel();
        venue5 = new javax.swing.JLabel();
        date5 = new javax.swing.JLabel();
        camFlag = new javax.swing.JLabel();
        v4 = new javax.swing.JLabel();
        fixture4 = new javax.swing.JPanel();
        venue4 = new javax.swing.JLabel();
        date4 = new javax.swing.JLabel();
        camLbl2 = new javax.swing.JLabel();
        croLbl2 = new javax.swing.JLabel();
        camFlag3 = new javax.swing.JLabel();
        brazilFlag = new javax.swing.JLabel();
        croFlag = new javax.swing.JLabel();
        brazilLbl2 = new javax.swing.JLabel();
        v3 = new javax.swing.JLabel();
        fixture3 = new javax.swing.JPanel();
        venue3 = new javax.swing.JLabel();
        date3 = new javax.swing.JLabel();
        mexLbl2 = new javax.swing.JLabel();
        mexFlag3 = new javax.swing.JLabel();
        brazilFlag3 = new javax.swing.JLabel();
        mexLbl = new javax.swing.JLabel();
        v2 = new javax.swing.JLabel();
        fixture2 = new javax.swing.JPanel();
        venue2 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        camLbl = new javax.swing.JLabel();
        mexFlag2 = new javax.swing.JLabel();
        camFlag2 = new javax.swing.JLabel();
        v1 = new javax.swing.JLabel();
        fixture1 = new javax.swing.JPanel();
        venue1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        brazilLbl = new javax.swing.JLabel();
        croLbl = new javax.swing.JLabel();
        brazilFlag2 = new javax.swing.JLabel();
        croFlag3 = new javax.swing.JLabel();
        groupALbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        taskbar = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jLabel4.setText("jLabel4");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        v6.setText("v");
        jLayeredPane1.add(v6);
        v6.setBounds(160, 560, 6, 14);

        fixture6.setBackground(new java.awt.Color(255, 255, 0));

        venue6.setText("Recife");

        date6.setText("23/06 17:00");

        javax.swing.GroupLayout fixture6Layout = new javax.swing.GroupLayout(fixture6);
        fixture6.setLayout(fixture6Layout);
        fixture6Layout.setHorizontalGroup(
            fixture6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(venue6)
                .addContainerGap())
        );
        fixture6Layout.setVerticalGroup(
            fixture6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue6)
                    .addComponent(date6)))
        );

        jLayeredPane1.add(fixture6);
        fixture6.setBounds(20, 530, 300, 14);

        croLbl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        croLbl3.setText("Croatia");
        jLayeredPane1.add(croLbl3);
        croLbl3.setBounds(20, 590, 43, 17);

        mexLbl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mexLbl3.setText("Mexico");
        jLayeredPane1.add(mexLbl3);
        mexLbl3.setBounds(260, 590, 50, 17);

        croFlag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Croatia.png"))); // NOI18N
        croFlag2.setText("jLabel1");
        jLayeredPane1.add(croFlag2);
        croFlag2.setBounds(250, 390, 65, 40);

        mexFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Mexico.png"))); // NOI18N
        mexFlag.setText("jLabel2");
        jLayeredPane1.add(mexFlag);
        mexFlag.setBounds(20, 220, 65, 40);

        braLbl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        braLbl3.setText("Brazil");
        jLayeredPane1.add(braLbl3);
        braLbl3.setBounds(260, 510, 30, 17);

        v5.setText("v");
        jLayeredPane1.add(v5);
        v5.setBounds(160, 470, 6, 14);

        camLbl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        camLbl3.setText("Cameroon");
        jLayeredPane1.add(camLbl3);
        camLbl3.setBounds(20, 510, 70, 17);

        fixture5.setBackground(new java.awt.Color(255, 255, 0));

        venue5.setText("Brasilia");

        date5.setText("23/06 17:00");

        javax.swing.GroupLayout fixture5Layout = new javax.swing.GroupLayout(fixture5);
        fixture5.setLayout(fixture5Layout);
        fixture5Layout.setHorizontalGroup(
            fixture5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(venue5)
                .addContainerGap())
        );
        fixture5Layout.setVerticalGroup(
            fixture5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue5)
                    .addComponent(date5)))
        );

        jLayeredPane1.add(fixture5);
        fixture5.setBounds(20, 450, 300, 14);

        camFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Cameroon.png"))); // NOI18N
        camFlag.setText("jLabel1");
        jLayeredPane1.add(camFlag);
        camFlag.setBounds(250, 220, 65, 40);

        v4.setText("v");
        jLayeredPane1.add(v4);
        v4.setBounds(160, 400, 6, 14);

        fixture4.setBackground(new java.awt.Color(255, 255, 0));

        venue4.setText("Manaus");

        date4.setText("18/06 18:00");

        javax.swing.GroupLayout fixture4Layout = new javax.swing.GroupLayout(fixture4);
        fixture4.setLayout(fixture4Layout);
        fixture4Layout.setHorizontalGroup(
            fixture4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(venue4)
                .addContainerGap())
        );
        fixture4Layout.setVerticalGroup(
            fixture4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue4)
                    .addComponent(date4)))
        );

        jLayeredPane1.add(fixture4);
        fixture4.setBounds(20, 370, 300, 14);

        camLbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        camLbl2.setText("Cameroon");
        jLayeredPane1.add(camLbl2);
        camLbl2.setBounds(20, 430, 70, 17);

        croLbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        croLbl2.setText("Croatia");
        jLayeredPane1.add(croLbl2);
        croLbl2.setBounds(250, 430, 43, 17);

        camFlag3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Cameroon.png"))); // NOI18N
        camFlag3.setText("jLabel1");
        jLayeredPane1.add(camFlag3);
        camFlag3.setBounds(20, 470, 65, 40);

        brazilFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Brazil.png"))); // NOI18N
        brazilFlag.setText("jLabel2");
        jLayeredPane1.add(brazilFlag);
        brazilFlag.setBounds(20, 130, 65, 40);

        croFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Croatia.png"))); // NOI18N
        croFlag.setText("jLabel1");
        jLayeredPane1.add(croFlag);
        croFlag.setBounds(250, 130, 65, 40);

        brazilLbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        brazilLbl2.setText("Brazil");
        jLayeredPane1.add(brazilLbl2);
        brazilLbl2.setBounds(30, 350, 30, 17);

        v3.setText("v");
        jLayeredPane1.add(v3);
        v3.setBounds(160, 340, 6, 14);

        fixture3.setBackground(new java.awt.Color(255, 255, 0));

        venue3.setText("Fortaleza");

        date3.setText("17/06 16:00");

        javax.swing.GroupLayout fixture3Layout = new javax.swing.GroupLayout(fixture3);
        fixture3.setLayout(fixture3Layout);
        fixture3Layout.setHorizontalGroup(
            fixture3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(venue3)
                .addContainerGap())
        );
        fixture3Layout.setVerticalGroup(
            fixture3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue3)
                    .addComponent(date3)))
        );

        jLayeredPane1.add(fixture3);
        fixture3.setBounds(20, 290, 300, 14);

        mexLbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mexLbl2.setText("Mexico");
        jLayeredPane1.add(mexLbl2);
        mexLbl2.setBounds(260, 350, 50, 17);

        mexFlag3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Mexico.png"))); // NOI18N
        mexFlag3.setText("jLabel2");
        jLayeredPane1.add(mexFlag3);
        mexFlag3.setBounds(250, 550, 65, 40);

        brazilFlag3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Brazil.png"))); // NOI18N
        brazilFlag3.setText("jLabel2");
        jLayeredPane1.add(brazilFlag3);
        brazilFlag3.setBounds(250, 470, 65, 40);

        mexLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mexLbl.setText("Mexico");
        jLayeredPane1.add(mexLbl);
        mexLbl.setBounds(30, 260, 50, 17);

        v2.setText("v");
        jLayeredPane1.add(v2);
        v2.setBounds(160, 260, 6, 14);

        fixture2.setBackground(new java.awt.Color(255, 255, 0));

        venue2.setText("Natal");

        date2.setText("13/06 13:00");

        javax.swing.GroupLayout fixture2Layout = new javax.swing.GroupLayout(fixture2);
        fixture2.setLayout(fixture2Layout);
        fixture2Layout.setHorizontalGroup(
            fixture2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(date2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(venue2)
                .addContainerGap())
        );
        fixture2Layout.setVerticalGroup(
            fixture2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue2)
                    .addComponent(date2)))
        );

        jLayeredPane1.add(fixture2);
        fixture2.setBounds(20, 200, 300, 14);

        camLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        camLbl.setText("Cameroon");
        jLayeredPane1.add(camLbl);
        camLbl.setBounds(250, 260, 70, 17);

        mexFlag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Mexico.png"))); // NOI18N
        mexFlag2.setText("jLabel2");
        jLayeredPane1.add(mexFlag2);
        mexFlag2.setBounds(250, 310, 65, 40);

        camFlag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Cameroon.png"))); // NOI18N
        camFlag2.setText("jLabel1");
        jLayeredPane1.add(camFlag2);
        camFlag2.setBounds(20, 390, 65, 40);

        v1.setText("v");
        jLayeredPane1.add(v1);
        v1.setBounds(160, 170, 6, 14);

        fixture1.setBackground(new java.awt.Color(255, 255, 0));

        venue1.setText("Sao Paulo");

        date1.setText("12/06 17:00");

        javax.swing.GroupLayout fixture1Layout = new javax.swing.GroupLayout(fixture1);
        fixture1.setLayout(fixture1Layout);
        fixture1Layout.setHorizontalGroup(
            fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(date1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(venue1)
                .addContainerGap())
        );
        fixture1Layout.setVerticalGroup(
            fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue1)
                    .addComponent(date1)))
        );

        jLayeredPane1.add(fixture1);
        fixture1.setBounds(20, 110, 300, 14);

        brazilLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        brazilLbl.setText("Brazil");
        jLayeredPane1.add(brazilLbl);
        brazilLbl.setBounds(30, 170, 30, 17);

        croLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        croLbl.setText("Croatia");
        jLayeredPane1.add(croLbl);
        croLbl.setBounds(250, 170, 43, 17);

        brazilFlag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Brazil.png"))); // NOI18N
        brazilFlag2.setText("jLabel2");
        jLayeredPane1.add(brazilFlag2);
        brazilFlag2.setBounds(20, 310, 65, 40);

        croFlag3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Croatia.png"))); // NOI18N
        croFlag3.setText("jLabel1");
        jLayeredPane1.add(croFlag3);
        croFlag3.setBounds(20, 550, 65, 40);

        groupALbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        groupALbl.setForeground(new java.awt.Color(255, 255, 255));
        groupALbl.setText("Group A");
        jLayeredPane1.add(groupALbl);
        groupALbl.setBounds(120, 60, 100, 50);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fixtures/back.png"))); // NOI18N
        backBtn.setOpaque(false);
        backBtn.setOpaque(false);
        backBtn.setContentAreaFilled( false );
        backBtn.setBorder( null );
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(backBtn);
        backBtn.setBounds(10, 10, 80, 50);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fixtures/home.png"))); // NOI18N
        homeBtn.setOpaque(false);
        homeBtn.setOpaque(false);
        homeBtn.setContentAreaFilled( false );
        homeBtn.setBorder( null );
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(homeBtn);
        homeBtn.setBounds(270, 10, 70, 50);

        taskbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Taskbar.png"))); // NOI18N
        taskbar.setText("jLabel2");
        jLayeredPane1.add(taskbar);
        taskbar.setBounds(0, -10, 360, 140);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        jLayeredPane1.add(bg);
        bg.setBounds(0, 0, 360, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        GroupFixtures gf = new GroupFixtures();
        gf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomeScreen h = new HomeScreen();
        h.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupA().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel braLbl3;
    private javax.swing.JLabel brazilFlag;
    private javax.swing.JLabel brazilFlag2;
    private javax.swing.JLabel brazilFlag3;
    private javax.swing.JLabel brazilLbl;
    private javax.swing.JLabel brazilLbl2;
    private javax.swing.JLabel camFlag;
    private javax.swing.JLabel camFlag2;
    private javax.swing.JLabel camFlag3;
    private javax.swing.JLabel camLbl;
    private javax.swing.JLabel camLbl2;
    private javax.swing.JLabel camLbl3;
    private javax.swing.JLabel croFlag;
    private javax.swing.JLabel croFlag2;
    private javax.swing.JLabel croFlag3;
    private javax.swing.JLabel croLbl;
    private javax.swing.JLabel croLbl2;
    private javax.swing.JLabel croLbl3;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel date3;
    private javax.swing.JLabel date4;
    private javax.swing.JLabel date5;
    private javax.swing.JLabel date6;
    private javax.swing.JPanel fixture1;
    private javax.swing.JPanel fixture2;
    private javax.swing.JPanel fixture3;
    private javax.swing.JPanel fixture4;
    private javax.swing.JPanel fixture5;
    private javax.swing.JPanel fixture6;
    private javax.swing.JLabel groupALbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel mexFlag;
    private javax.swing.JLabel mexFlag2;
    private javax.swing.JLabel mexFlag3;
    private javax.swing.JLabel mexLbl;
    private javax.swing.JLabel mexLbl2;
    private javax.swing.JLabel mexLbl3;
    private javax.swing.JLabel taskbar;
    private javax.swing.JLabel v1;
    private javax.swing.JLabel v2;
    private javax.swing.JLabel v3;
    private javax.swing.JLabel v4;
    private javax.swing.JLabel v5;
    private javax.swing.JLabel v6;
    private javax.swing.JLabel venue1;
    private javax.swing.JLabel venue2;
    private javax.swing.JLabel venue3;
    private javax.swing.JLabel venue4;
    private javax.swing.JLabel venue5;
    private javax.swing.JLabel venue6;
    // End of variables declaration//GEN-END:variables
}
