/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package worldcupapp;

/**
 *
 * @author Nathan Ryan x13448212 Group 7
 */
public class GroupG extends javax.swing.JFrame {

    /**
     * Creates new form GroupG
     */
    public GroupG() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        v6 = new javax.swing.JLabel();
        fixture8 = new javax.swing.JPanel();
        venue8 = new javax.swing.JLabel();
        date8 = new javax.swing.JLabel();
        porFlag3 = new javax.swing.JLabel();
        ghanaLbl3 = new javax.swing.JLabel();
        porFlag2 = new javax.swing.JLabel();
        ghanaFlag = new javax.swing.JLabel();
        gerLbl3 = new javax.swing.JLabel();
        v5 = new javax.swing.JLabel();
        usaLbl3 = new javax.swing.JLabel();
        fixture5 = new javax.swing.JPanel();
        venue5 = new javax.swing.JLabel();
        date5 = new javax.swing.JLabel();
        usaFlag = new javax.swing.JLabel();
        v4 = new javax.swing.JLabel();
        fixture4 = new javax.swing.JPanel();
        venue4 = new javax.swing.JLabel();
        date4 = new javax.swing.JLabel();
        usaLbl2 = new javax.swing.JLabel();
        porLbl2 = new javax.swing.JLabel();
        usaFlag3 = new javax.swing.JLabel();
        gerFlag = new javax.swing.JLabel();
        porFlag = new javax.swing.JLabel();
        gerLbl2 = new javax.swing.JLabel();
        v3 = new javax.swing.JLabel();
        fixture3 = new javax.swing.JPanel();
        venue3 = new javax.swing.JLabel();
        date3 = new javax.swing.JLabel();
        ghanaLbl2 = new javax.swing.JLabel();
        ghanaFlag3 = new javax.swing.JLabel();
        gerFlag3 = new javax.swing.JLabel();
        ghanaLbl = new javax.swing.JLabel();
        v2 = new javax.swing.JLabel();
        fixture2 = new javax.swing.JPanel();
        venue2 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        usaLbl = new javax.swing.JLabel();
        ghanaFlag2 = new javax.swing.JLabel();
        usaFlag2 = new javax.swing.JLabel();
        v1 = new javax.swing.JLabel();
        fixture1 = new javax.swing.JPanel();
        venue1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        gerLbl = new javax.swing.JLabel();
        porLbl = new javax.swing.JLabel();
        gerFlag2 = new javax.swing.JLabel();
        proFlag3 = new javax.swing.JLabel();
        groupGLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        taskbar = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        v6.setText("v");
        jLayeredPane1.add(v6);
        v6.setBounds(160, 560, 6, 14);

        fixture8.setBackground(new java.awt.Color(255, 255, 0));

        venue8.setText("Brasilia");

        date8.setText("26/06 13:00");

        javax.swing.GroupLayout fixture8Layout = new javax.swing.GroupLayout(fixture8);
        fixture8.setLayout(fixture8Layout);
        fixture8Layout.setHorizontalGroup(
            fixture8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(venue8)
                .addContainerGap())
        );
        fixture8Layout.setVerticalGroup(
            fixture8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue8)
                    .addComponent(date8)))
        );

        jLayeredPane1.add(fixture8);
        fixture8.setBounds(20, 530, 300, 14);

        porFlag3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        porFlag3.setText("Portugal");
        jLayeredPane1.add(porFlag3);
        porFlag3.setBounds(20, 590, 150, 17);

        ghanaLbl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ghanaLbl3.setText("Ghana");
        jLayeredPane1.add(ghanaLbl3);
        ghanaLbl3.setBounds(250, 590, 80, 17);

        porFlag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Portugal.png"))); // NOI18N
        porFlag2.setText("jLabel1");
        jLayeredPane1.add(porFlag2);
        porFlag2.setBounds(250, 390, 65, 40);

        ghanaFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Ghana.png"))); // NOI18N
        ghanaFlag.setText("jLabel2");
        jLayeredPane1.add(ghanaFlag);
        ghanaFlag.setBounds(20, 220, 65, 40);

        gerLbl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gerLbl3.setText("Germany");
        jLayeredPane1.add(gerLbl3);
        gerLbl3.setBounds(250, 510, 70, 17);

        v5.setText("v");
        jLayeredPane1.add(v5);
        v5.setBounds(160, 470, 6, 14);

        usaLbl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usaLbl3.setText("USA");
        jLayeredPane1.add(usaLbl3);
        usaLbl3.setBounds(20, 510, 60, 17);

        fixture5.setBackground(new java.awt.Color(255, 255, 0));

        venue5.setText("Recife");

        date5.setText("26/06 13:00");

        javax.swing.GroupLayout fixture5Layout = new javax.swing.GroupLayout(fixture5);
        fixture5.setLayout(fixture5Layout);
        fixture5Layout.setHorizontalGroup(
            fixture5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(venue5)
                .addContainerGap())
        );
        fixture5Layout.setVerticalGroup(
            fixture5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue5)
                    .addComponent(date5)))
        );

        jLayeredPane1.add(fixture5);
        fixture5.setBounds(20, 450, 300, 14);

        usaFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/United-States.png"))); // NOI18N
        usaFlag.setText("jLabel1");
        jLayeredPane1.add(usaFlag);
        usaFlag.setBounds(250, 220, 65, 40);

        v4.setText("v");
        jLayeredPane1.add(v4);
        v4.setBounds(160, 400, 6, 14);

        fixture4.setBackground(new java.awt.Color(255, 255, 0));

        venue4.setText("Manaus");

        date4.setText("22/06 18:00");

        javax.swing.GroupLayout fixture4Layout = new javax.swing.GroupLayout(fixture4);
        fixture4.setLayout(fixture4Layout);
        fixture4Layout.setHorizontalGroup(
            fixture4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(venue4)
                .addContainerGap())
        );
        fixture4Layout.setVerticalGroup(
            fixture4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue4)
                    .addComponent(date4)))
        );

        jLayeredPane1.add(fixture4);
        fixture4.setBounds(20, 370, 300, 14);

        usaLbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usaLbl2.setText("USA");
        jLayeredPane1.add(usaLbl2);
        usaLbl2.setBounds(20, 430, 60, 17);

        porLbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        porLbl2.setText("Portugal");
        jLayeredPane1.add(porLbl2);
        porLbl2.setBounds(250, 430, 110, 17);

        usaFlag3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/United-States.png"))); // NOI18N
        usaFlag3.setText("jLabel1");
        jLayeredPane1.add(usaFlag3);
        usaFlag3.setBounds(20, 470, 65, 40);

        gerFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Germany.png"))); // NOI18N
        gerFlag.setText("jLabel2");
        jLayeredPane1.add(gerFlag);
        gerFlag.setBounds(20, 130, 65, 40);

        porFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Portugal.png"))); // NOI18N
        porFlag.setText("jLabel1");
        jLayeredPane1.add(porFlag);
        porFlag.setBounds(250, 130, 65, 40);

        gerLbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gerLbl2.setText("Germany");
        jLayeredPane1.add(gerLbl2);
        gerLbl2.setBounds(20, 350, 70, 17);

        v3.setText("v");
        jLayeredPane1.add(v3);
        v3.setBounds(160, 340, 6, 14);

        fixture3.setBackground(new java.awt.Color(255, 255, 0));

        venue3.setText("Fortaleza");

        date3.setText("21/06 16:00");

        javax.swing.GroupLayout fixture3Layout = new javax.swing.GroupLayout(fixture3);
        fixture3.setLayout(fixture3Layout);
        fixture3Layout.setHorizontalGroup(
            fixture3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(venue3)
                .addContainerGap())
        );
        fixture3Layout.setVerticalGroup(
            fixture3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue3)
                    .addComponent(date3)))
        );

        jLayeredPane1.add(fixture3);
        fixture3.setBounds(20, 290, 300, 14);

        ghanaLbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ghanaLbl2.setText("Ghana");
        jLayeredPane1.add(ghanaLbl2);
        ghanaLbl2.setBounds(250, 350, 80, 17);

        ghanaFlag3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Ghana.png"))); // NOI18N
        ghanaFlag3.setText("jLabel2");
        jLayeredPane1.add(ghanaFlag3);
        ghanaFlag3.setBounds(250, 550, 65, 40);

        gerFlag3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Germany.png"))); // NOI18N
        gerFlag3.setText("jLabel2");
        jLayeredPane1.add(gerFlag3);
        gerFlag3.setBounds(250, 470, 65, 40);

        ghanaLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ghanaLbl.setText("Ghana");
        jLayeredPane1.add(ghanaLbl);
        ghanaLbl.setBounds(20, 260, 80, 17);

        v2.setText("v");
        jLayeredPane1.add(v2);
        v2.setBounds(160, 260, 6, 14);

        fixture2.setBackground(new java.awt.Color(255, 255, 0));

        venue2.setText("Natal");

        date2.setText("16/06 19:00");

        javax.swing.GroupLayout fixture2Layout = new javax.swing.GroupLayout(fixture2);
        fixture2.setLayout(fixture2Layout);
        fixture2Layout.setHorizontalGroup(
            fixture2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(date2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(venue2)
                .addContainerGap())
        );
        fixture2Layout.setVerticalGroup(
            fixture2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue2)
                    .addComponent(date2)))
        );

        jLayeredPane1.add(fixture2);
        fixture2.setBounds(20, 200, 300, 14);

        usaLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usaLbl.setText("USA");
        jLayeredPane1.add(usaLbl);
        usaLbl.setBounds(250, 260, 60, 17);

        ghanaFlag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Ghana.png"))); // NOI18N
        ghanaFlag2.setText("jLabel2");
        jLayeredPane1.add(ghanaFlag2);
        ghanaFlag2.setBounds(250, 310, 65, 40);

        usaFlag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/United-States.png"))); // NOI18N
        usaFlag2.setText("jLabel1");
        jLayeredPane1.add(usaFlag2);
        usaFlag2.setBounds(20, 390, 65, 40);

        v1.setText("v");
        jLayeredPane1.add(v1);
        v1.setBounds(160, 170, 6, 14);

        fixture1.setBackground(new java.awt.Color(255, 255, 0));

        venue1.setText("Salvador");

        date1.setText("16/06 13:00");

        javax.swing.GroupLayout fixture1Layout = new javax.swing.GroupLayout(fixture1);
        fixture1.setLayout(fixture1Layout);
        fixture1Layout.setHorizontalGroup(
            fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(date1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(venue1)
                .addContainerGap())
        );
        fixture1Layout.setVerticalGroup(
            fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue1)
                    .addComponent(date1)))
        );

        jLayeredPane1.add(fixture1);
        fixture1.setBounds(20, 110, 300, 14);

        gerLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gerLbl.setText("Germany");
        jLayeredPane1.add(gerLbl);
        gerLbl.setBounds(20, 170, 70, 17);

        porLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        porLbl.setText("Portugal");
        jLayeredPane1.add(porLbl);
        porLbl.setBounds(255, 170, 100, 17);

        gerFlag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Germany.png"))); // NOI18N
        gerFlag2.setText("jLabel2");
        jLayeredPane1.add(gerFlag2);
        gerFlag2.setBounds(20, 310, 65, 40);

        proFlag3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Portugal.png"))); // NOI18N
        proFlag3.setText("jLabel1");
        jLayeredPane1.add(proFlag3);
        proFlag3.setBounds(20, 550, 65, 40);

        groupGLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        groupGLbl.setForeground(new java.awt.Color(255, 255, 255));
        groupGLbl.setText("Group G");
        jLayeredPane1.add(groupGLbl);
        groupGLbl.setBounds(120, 60, 100, 50);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fixtures/back.png"))); // NOI18N
        backBtn.setOpaque(false);
        backBtn.setOpaque(false);
        backBtn.setContentAreaFilled( false );
        backBtn.setBorder( null );
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(backBtn);
        backBtn.setBounds(10, 10, 80, 50);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fixtures/home.png"))); // NOI18N
        homeBtn.setOpaque(false);
        homeBtn.setOpaque(false);
        homeBtn.setContentAreaFilled( false );
        homeBtn.setBorder( null );
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(homeBtn);
        homeBtn.setBounds(270, 10, 70, 50);

        taskbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Taskbar.png"))); // NOI18N
        taskbar.setText("jLabel2");
        jLayeredPane1.add(taskbar);
        taskbar.setBounds(0, -10, 360, 140);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        jLayeredPane1.add(bg);
        bg.setBounds(0, 0, 360, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        GroupFixtures gf = new GroupFixtures();
        gf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomeScreen h = new HomeScreen();
        h.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupG().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel date3;
    private javax.swing.JLabel date4;
    private javax.swing.JLabel date5;
    private javax.swing.JLabel date8;
    private javax.swing.JPanel fixture1;
    private javax.swing.JPanel fixture2;
    private javax.swing.JPanel fixture3;
    private javax.swing.JPanel fixture4;
    private javax.swing.JPanel fixture5;
    private javax.swing.JPanel fixture8;
    private javax.swing.JLabel gerFlag;
    private javax.swing.JLabel gerFlag2;
    private javax.swing.JLabel gerFlag3;
    private javax.swing.JLabel gerLbl;
    private javax.swing.JLabel gerLbl2;
    private javax.swing.JLabel gerLbl3;
    private javax.swing.JLabel ghanaFlag;
    private javax.swing.JLabel ghanaFlag2;
    private javax.swing.JLabel ghanaFlag3;
    private javax.swing.JLabel ghanaLbl;
    private javax.swing.JLabel ghanaLbl2;
    private javax.swing.JLabel ghanaLbl3;
    private javax.swing.JLabel groupGLbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel porFlag;
    private javax.swing.JLabel porFlag2;
    private javax.swing.JLabel porFlag3;
    private javax.swing.JLabel porLbl;
    private javax.swing.JLabel porLbl2;
    private javax.swing.JLabel proFlag3;
    private javax.swing.JLabel taskbar;
    private javax.swing.JLabel usaFlag;
    private javax.swing.JLabel usaFlag2;
    private javax.swing.JLabel usaFlag3;
    private javax.swing.JLabel usaLbl;
    private javax.swing.JLabel usaLbl2;
    private javax.swing.JLabel usaLbl3;
    private javax.swing.JLabel v1;
    private javax.swing.JLabel v2;
    private javax.swing.JLabel v3;
    private javax.swing.JLabel v4;
    private javax.swing.JLabel v5;
    private javax.swing.JLabel v6;
    private javax.swing.JLabel venue1;
    private javax.swing.JLabel venue2;
    private javax.swing.JLabel venue3;
    private javax.swing.JLabel venue4;
    private javax.swing.JLabel venue5;
    private javax.swing.JLabel venue8;
    // End of variables declaration//GEN-END:variables
}
