/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package worldcupapp;

/**
 *
 * @author Nathan Ryan x13448212 Group 7
 */
public class GroupE extends javax.swing.JFrame {

    /**
     * Creates new form GroupE
     */
    public GroupE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        v6 = new javax.swing.JLabel();
        fixture8 = new javax.swing.JPanel();
        venue8 = new javax.swing.JLabel();
        date8 = new javax.swing.JLabel();
        ecuLbl3 = new javax.swing.JLabel();
        franceLbl3 = new javax.swing.JLabel();
        ecuFlag2 = new javax.swing.JLabel();
        franceFlag = new javax.swing.JLabel();
        switzLbl3 = new javax.swing.JLabel();
        v5 = new javax.swing.JLabel();
        honLbl3 = new javax.swing.JLabel();
        fixture5 = new javax.swing.JPanel();
        venue5 = new javax.swing.JLabel();
        date5 = new javax.swing.JLabel();
        honFlag = new javax.swing.JLabel();
        v4 = new javax.swing.JLabel();
        fixture4 = new javax.swing.JPanel();
        venue4 = new javax.swing.JLabel();
        date4 = new javax.swing.JLabel();
        honLbl2 = new javax.swing.JLabel();
        ecuLbl2 = new javax.swing.JLabel();
        honFlag3 = new javax.swing.JLabel();
        switzFlag = new javax.swing.JLabel();
        ecuFlag = new javax.swing.JLabel();
        switzLbl2 = new javax.swing.JLabel();
        v3 = new javax.swing.JLabel();
        fixture3 = new javax.swing.JPanel();
        venue3 = new javax.swing.JLabel();
        date3 = new javax.swing.JLabel();
        franceLbl2 = new javax.swing.JLabel();
        franceFlag3 = new javax.swing.JLabel();
        switzFlag3 = new javax.swing.JLabel();
        franceLbl = new javax.swing.JLabel();
        v2 = new javax.swing.JLabel();
        fixture2 = new javax.swing.JPanel();
        venue2 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        honLbl = new javax.swing.JLabel();
        franceFlag2 = new javax.swing.JLabel();
        honFlag2 = new javax.swing.JLabel();
        v1 = new javax.swing.JLabel();
        fixture1 = new javax.swing.JPanel();
        venue1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        switzLbl = new javax.swing.JLabel();
        ecuLbl = new javax.swing.JLabel();
        switzFlag2 = new javax.swing.JLabel();
        ecuFlag3 = new javax.swing.JLabel();
        groupELbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        taskbar = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        v6.setText("v");
        jLayeredPane1.add(v6);
        v6.setBounds(160, 560, 6, 14);

        fixture8.setBackground(new java.awt.Color(255, 255, 0));

        venue8.setText("Rio De Janeiro");

        date8.setText("25/06 17:00");

        javax.swing.GroupLayout fixture8Layout = new javax.swing.GroupLayout(fixture8);
        fixture8.setLayout(fixture8Layout);
        fixture8Layout.setHorizontalGroup(
            fixture8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(venue8)
                .addContainerGap())
        );
        fixture8Layout.setVerticalGroup(
            fixture8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue8)
                    .addComponent(date8)))
        );

        jLayeredPane1.add(fixture8);
        fixture8.setBounds(20, 530, 300, 14);

        ecuLbl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ecuLbl3.setText("Ecuador");
        jLayeredPane1.add(ecuLbl3);
        ecuLbl3.setBounds(20, 590, 70, 17);

        franceLbl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        franceLbl3.setText("France");
        jLayeredPane1.add(franceLbl3);
        franceLbl3.setBounds(250, 590, 80, 17);

        ecuFlag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Ecuador.png"))); // NOI18N
        ecuFlag2.setText("jLabel1");
        jLayeredPane1.add(ecuFlag2);
        ecuFlag2.setBounds(250, 390, 65, 40);

        franceFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/France.png"))); // NOI18N
        franceFlag.setText("jLabel2");
        jLayeredPane1.add(franceFlag);
        franceFlag.setBounds(20, 220, 65, 40);

        switzLbl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        switzLbl3.setText("Switzerland");
        jLayeredPane1.add(switzLbl3);
        switzLbl3.setBounds(250, 510, 70, 17);

        v5.setText("v");
        jLayeredPane1.add(v5);
        v5.setBounds(160, 470, 6, 14);

        honLbl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        honLbl3.setText("Honduras");
        jLayeredPane1.add(honLbl3);
        honLbl3.setBounds(20, 510, 60, 17);

        fixture5.setBackground(new java.awt.Color(255, 255, 0));

        venue5.setText("Manaus");

        date5.setText("25/06 16:00");

        javax.swing.GroupLayout fixture5Layout = new javax.swing.GroupLayout(fixture5);
        fixture5.setLayout(fixture5Layout);
        fixture5Layout.setHorizontalGroup(
            fixture5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(venue5)
                .addContainerGap())
        );
        fixture5Layout.setVerticalGroup(
            fixture5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue5)
                    .addComponent(date5)))
        );

        jLayeredPane1.add(fixture5);
        fixture5.setBounds(20, 450, 300, 14);

        honFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Honduras.png"))); // NOI18N
        honFlag.setText("jLabel1");
        jLayeredPane1.add(honFlag);
        honFlag.setBounds(250, 220, 65, 40);

        v4.setText("v");
        jLayeredPane1.add(v4);
        v4.setBounds(160, 400, 6, 14);

        fixture4.setBackground(new java.awt.Color(255, 255, 0));

        venue4.setText("Curitiba");

        date4.setText("20/06 19:00");

        javax.swing.GroupLayout fixture4Layout = new javax.swing.GroupLayout(fixture4);
        fixture4.setLayout(fixture4Layout);
        fixture4Layout.setHorizontalGroup(
            fixture4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(venue4)
                .addContainerGap())
        );
        fixture4Layout.setVerticalGroup(
            fixture4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue4)
                    .addComponent(date4)))
        );

        jLayeredPane1.add(fixture4);
        fixture4.setBounds(20, 370, 300, 14);

        honLbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        honLbl2.setText("Honduras");
        jLayeredPane1.add(honLbl2);
        honLbl2.setBounds(20, 430, 60, 17);

        ecuLbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ecuLbl2.setText("Ecuador");
        jLayeredPane1.add(ecuLbl2);
        ecuLbl2.setBounds(250, 430, 70, 17);

        honFlag3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Honduras.png"))); // NOI18N
        honFlag3.setText("jLabel1");
        jLayeredPane1.add(honFlag3);
        honFlag3.setBounds(20, 470, 65, 40);

        switzFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Switzerland.png"))); // NOI18N
        switzFlag.setText("jLabel2");
        jLayeredPane1.add(switzFlag);
        switzFlag.setBounds(20, 130, 65, 40);

        ecuFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Ecuador.png"))); // NOI18N
        ecuFlag.setText("jLabel1");
        jLayeredPane1.add(ecuFlag);
        ecuFlag.setBounds(250, 130, 65, 40);

        switzLbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        switzLbl2.setText("Switzerland");
        jLayeredPane1.add(switzLbl2);
        switzLbl2.setBounds(20, 350, 70, 17);

        v3.setText("v");
        jLayeredPane1.add(v3);
        v3.setBounds(160, 340, 6, 14);

        fixture3.setBackground(new java.awt.Color(255, 255, 0));

        venue3.setText("Salvador");

        date3.setText("20/06 16:00");

        javax.swing.GroupLayout fixture3Layout = new javax.swing.GroupLayout(fixture3);
        fixture3.setLayout(fixture3Layout);
        fixture3Layout.setHorizontalGroup(
            fixture3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(venue3)
                .addContainerGap())
        );
        fixture3Layout.setVerticalGroup(
            fixture3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue3)
                    .addComponent(date3)))
        );

        jLayeredPane1.add(fixture3);
        fixture3.setBounds(20, 290, 300, 14);

        franceLbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        franceLbl2.setText("France");
        jLayeredPane1.add(franceLbl2);
        franceLbl2.setBounds(250, 350, 80, 17);

        franceFlag3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/France.png"))); // NOI18N
        franceFlag3.setText("jLabel2");
        jLayeredPane1.add(franceFlag3);
        franceFlag3.setBounds(250, 550, 65, 40);

        switzFlag3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Switzerland.png"))); // NOI18N
        switzFlag3.setText("jLabel2");
        jLayeredPane1.add(switzFlag3);
        switzFlag3.setBounds(250, 470, 65, 40);

        franceLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        franceLbl.setText("France");
        jLayeredPane1.add(franceLbl);
        franceLbl.setBounds(20, 260, 80, 17);

        v2.setText("v");
        jLayeredPane1.add(v2);
        v2.setBounds(160, 260, 6, 14);

        fixture2.setBackground(new java.awt.Color(255, 255, 0));

        venue2.setText("Porto Alegre");

        date2.setText("15/06 16:00");

        javax.swing.GroupLayout fixture2Layout = new javax.swing.GroupLayout(fixture2);
        fixture2.setLayout(fixture2Layout);
        fixture2Layout.setHorizontalGroup(
            fixture2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(date2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(venue2)
                .addContainerGap())
        );
        fixture2Layout.setVerticalGroup(
            fixture2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue2)
                    .addComponent(date2)))
        );

        jLayeredPane1.add(fixture2);
        fixture2.setBounds(20, 200, 300, 14);

        honLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        honLbl.setText("Honduras");
        jLayeredPane1.add(honLbl);
        honLbl.setBounds(250, 260, 60, 17);

        franceFlag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/France.png"))); // NOI18N
        franceFlag2.setText("jLabel2");
        jLayeredPane1.add(franceFlag2);
        franceFlag2.setBounds(250, 310, 65, 40);

        honFlag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Honduras.png"))); // NOI18N
        honFlag2.setText("jLabel1");
        jLayeredPane1.add(honFlag2);
        honFlag2.setBounds(20, 390, 65, 40);

        v1.setText("v");
        jLayeredPane1.add(v1);
        v1.setBounds(160, 170, 6, 14);

        fixture1.setBackground(new java.awt.Color(255, 255, 0));

        venue1.setText("Brasilia");

        date1.setText("15/06 13:00");

        javax.swing.GroupLayout fixture1Layout = new javax.swing.GroupLayout(fixture1);
        fixture1.setLayout(fixture1Layout);
        fixture1Layout.setHorizontalGroup(
            fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(date1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(venue1)
                .addContainerGap())
        );
        fixture1Layout.setVerticalGroup(
            fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue1)
                    .addComponent(date1)))
        );

        jLayeredPane1.add(fixture1);
        fixture1.setBounds(20, 110, 300, 14);

        switzLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        switzLbl.setText("Switzerland");
        jLayeredPane1.add(switzLbl);
        switzLbl.setBounds(20, 170, 70, 17);

        ecuLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ecuLbl.setText("Ecuador");
        jLayeredPane1.add(ecuLbl);
        ecuLbl.setBounds(250, 170, 70, 17);

        switzFlag2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Switzerland.png"))); // NOI18N
        switzFlag2.setText("jLabel2");
        jLayeredPane1.add(switzFlag2);
        switzFlag2.setBounds(20, 310, 65, 40);

        ecuFlag3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Ecuador.png"))); // NOI18N
        ecuFlag3.setText("jLabel1");
        jLayeredPane1.add(ecuFlag3);
        ecuFlag3.setBounds(20, 550, 65, 40);

        groupELbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        groupELbl.setForeground(new java.awt.Color(255, 255, 255));
        groupELbl.setText("Group E");
        jLayeredPane1.add(groupELbl);
        groupELbl.setBounds(120, 60, 100, 50);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fixtures/back.png"))); // NOI18N
        backBtn.setOpaque(false);
        backBtn.setOpaque(false);
        backBtn.setContentAreaFilled( false );
        backBtn.setBorder( null );
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(backBtn);
        backBtn.setBounds(10, 10, 80, 50);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fixtures/home.png"))); // NOI18N
        homeBtn.setOpaque(false);
        homeBtn.setOpaque(false);
        homeBtn.setContentAreaFilled( false );
        homeBtn.setBorder( null );
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(homeBtn);
        homeBtn.setBounds(270, 10, 70, 50);

        taskbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Taskbar.png"))); // NOI18N
        taskbar.setText("jLabel2");
        jLayeredPane1.add(taskbar);
        taskbar.setBounds(0, -10, 360, 140);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        jLayeredPane1.add(bg);
        bg.setBounds(0, 0, 360, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        GroupFixtures gf = new GroupFixtures();
        gf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomeScreen h = new HomeScreen();
        h.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupE().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel date3;
    private javax.swing.JLabel date4;
    private javax.swing.JLabel date5;
    private javax.swing.JLabel date8;
    private javax.swing.JLabel ecuFlag;
    private javax.swing.JLabel ecuFlag2;
    private javax.swing.JLabel ecuFlag3;
    private javax.swing.JLabel ecuLbl;
    private javax.swing.JLabel ecuLbl2;
    private javax.swing.JLabel ecuLbl3;
    private javax.swing.JPanel fixture1;
    private javax.swing.JPanel fixture2;
    private javax.swing.JPanel fixture3;
    private javax.swing.JPanel fixture4;
    private javax.swing.JPanel fixture5;
    private javax.swing.JPanel fixture8;
    private javax.swing.JLabel franceFlag;
    private javax.swing.JLabel franceFlag2;
    private javax.swing.JLabel franceFlag3;
    private javax.swing.JLabel franceLbl;
    private javax.swing.JLabel franceLbl2;
    private javax.swing.JLabel franceLbl3;
    private javax.swing.JLabel groupELbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel honFlag;
    private javax.swing.JLabel honFlag2;
    private javax.swing.JLabel honFlag3;
    private javax.swing.JLabel honLbl;
    private javax.swing.JLabel honLbl2;
    private javax.swing.JLabel honLbl3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel switzFlag;
    private javax.swing.JLabel switzFlag2;
    private javax.swing.JLabel switzFlag3;
    private javax.swing.JLabel switzLbl;
    private javax.swing.JLabel switzLbl2;
    private javax.swing.JLabel switzLbl3;
    private javax.swing.JLabel taskbar;
    private javax.swing.JLabel v1;
    private javax.swing.JLabel v2;
    private javax.swing.JLabel v3;
    private javax.swing.JLabel v4;
    private javax.swing.JLabel v5;
    private javax.swing.JLabel v6;
    private javax.swing.JLabel venue1;
    private javax.swing.JLabel venue2;
    private javax.swing.JLabel venue3;
    private javax.swing.JLabel venue4;
    private javax.swing.JLabel venue5;
    private javax.swing.JLabel venue8;
    // End of variables declaration//GEN-END:variables
}
