/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package worldcupapp;

/**
 *
 * @author Nathan Ryan x13448212 Group 7
 */
public class Quarters extends javax.swing.JFrame {

    /**
     * Creates new form Quarters
     */
    public Quarters() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        v4 = new javax.swing.JLabel();
        fixture4 = new javax.swing.JPanel();
        venue4 = new javax.swing.JLabel();
        date4 = new javax.swing.JLabel();
        matchLbl4 = new javax.swing.JLabel();
        w55Lbl = new javax.swing.JLabel();
        w56Lbl = new javax.swing.JLabel();
        w51Lbl = new javax.swing.JLabel();
        v3 = new javax.swing.JLabel();
        fixture3 = new javax.swing.JPanel();
        venue3 = new javax.swing.JLabel();
        date3 = new javax.swing.JLabel();
        matchLbl3 = new javax.swing.JLabel();
        w52Lbl = new javax.swing.JLabel();
        w53Lbl = new javax.swing.JLabel();
        v2 = new javax.swing.JLabel();
        fixture2 = new javax.swing.JPanel();
        venue2 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        matchLbl2 = new javax.swing.JLabel();
        w54Lbl = new javax.swing.JLabel();
        v1 = new javax.swing.JLabel();
        fixture1 = new javax.swing.JPanel();
        venue1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        matchLbl = new javax.swing.JLabel();
        w49Lbl = new javax.swing.JLabel();
        w50Lbl = new javax.swing.JLabel();
        qFinalsLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        taskbar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        v4.setText("v");
        jLayeredPane1.add(v4);
        v4.setBounds(140, 410, 6, 14);

        fixture4.setBackground(new java.awt.Color(255, 255, 0));

        venue4.setText("Brasilia");

        date4.setText("5/07 13:00");

        matchLbl4.setText("Match No");

        javax.swing.GroupLayout fixture4Layout = new javax.swing.GroupLayout(fixture4);
        fixture4.setLayout(fixture4Layout);
        fixture4Layout.setHorizontalGroup(
            fixture4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date4)
                .addGap(77, 77, 77)
                .addComponent(venue4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(matchLbl4))
        );
        fixture4Layout.setVerticalGroup(
            fixture4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue4)
                    .addComponent(date4)
                    .addComponent(matchLbl4)))
        );

        jLayeredPane1.add(fixture4);
        fixture4.setBounds(30, 380, 300, 14);

        w55Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        w55Lbl.setText("W55");
        jLayeredPane1.add(w55Lbl);
        w55Lbl.setBounds(30, 410, 100, 17);

        w56Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        w56Lbl.setText("W56");
        jLayeredPane1.add(w56Lbl);
        w56Lbl.setBounds(180, 410, 110, 17);

        w51Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        w51Lbl.setText("W51");
        jLayeredPane1.add(w51Lbl);
        w51Lbl.setBounds(30, 350, 70, 17);

        v3.setText("v");
        jLayeredPane1.add(v3);
        v3.setBounds(140, 350, 6, 14);

        fixture3.setBackground(new java.awt.Color(255, 255, 0));

        venue3.setText("Salvador");

        date3.setText("5/07 17:00");

        matchLbl3.setText("Match No");

        javax.swing.GroupLayout fixture3Layout = new javax.swing.GroupLayout(fixture3);
        fixture3.setLayout(fixture3Layout);
        fixture3Layout.setHorizontalGroup(
            fixture3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date3)
                .addGap(71, 71, 71)
                .addComponent(venue3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(matchLbl3))
        );
        fixture3Layout.setVerticalGroup(
            fixture3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue3)
                    .addComponent(date3)
                    .addComponent(matchLbl3)))
        );

        jLayeredPane1.add(fixture3);
        fixture3.setBounds(30, 320, 300, 14);

        w52Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        w52Lbl.setText("W52");
        jLayeredPane1.add(w52Lbl);
        w52Lbl.setBounds(180, 350, 80, 17);

        w53Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        w53Lbl.setText("W53");
        jLayeredPane1.add(w53Lbl);
        w53Lbl.setBounds(30, 290, 80, 17);

        v2.setText("v");
        jLayeredPane1.add(v2);
        v2.setBounds(140, 290, 6, 14);

        fixture2.setBackground(new java.awt.Color(255, 255, 0));

        venue2.setText("Rio De Janeiro");

        date2.setText("4/07 13:00");

        matchLbl2.setText("Match No");

        javax.swing.GroupLayout fixture2Layout = new javax.swing.GroupLayout(fixture2);
        fixture2.setLayout(fixture2Layout);
        fixture2Layout.setHorizontalGroup(
            fixture2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(date2)
                .addGap(60, 60, 60)
                .addComponent(venue2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(matchLbl2))
        );
        fixture2Layout.setVerticalGroup(
            fixture2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue2)
                    .addComponent(date2)
                    .addComponent(matchLbl2)))
        );

        jLayeredPane1.add(fixture2);
        fixture2.setBounds(30, 260, 300, 14);

        w54Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        w54Lbl.setText("W54");
        jLayeredPane1.add(w54Lbl);
        w54Lbl.setBounds(180, 290, 90, 17);

        v1.setText("v");
        jLayeredPane1.add(v1);
        v1.setBounds(140, 230, 6, 14);

        fixture1.setBackground(new java.awt.Color(255, 255, 0));

        venue1.setText("Fortaleza");

        date1.setText("4/07 17:00");

        matchLbl.setText("Match No");

        javax.swing.GroupLayout fixture1Layout = new javax.swing.GroupLayout(fixture1);
        fixture1.setLayout(fixture1Layout);
        fixture1Layout.setHorizontalGroup(
            fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(date1)
                .addGap(63, 63, 63)
                .addComponent(venue1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(matchLbl))
        );
        fixture1Layout.setVerticalGroup(
            fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue1)
                    .addComponent(date1)
                    .addComponent(matchLbl)))
        );

        jLayeredPane1.add(fixture1);
        fixture1.setBounds(30, 200, 300, 14);

        w49Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        w49Lbl.setText("W49");
        jLayeredPane1.add(w49Lbl);
        w49Lbl.setBounds(30, 230, 70, 17);

        w50Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        w50Lbl.setText("W50");
        jLayeredPane1.add(w50Lbl);
        w50Lbl.setBounds(190, 230, 100, 17);

        qFinalsLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        qFinalsLbl.setForeground(new java.awt.Color(255, 255, 255));
        qFinalsLbl.setText("Quarter Finals");
        jLayeredPane1.add(qFinalsLbl);
        qFinalsLbl.setBounds(120, 60, 130, 50);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fixtures/back.png"))); // NOI18N
        backBtn.setOpaque(false);
        backBtn.setOpaque(false);
        backBtn.setContentAreaFilled( false );
        backBtn.setBorder( null );
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(backBtn);
        backBtn.setBounds(10, 10, 80, 50);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fixtures/home.png"))); // NOI18N
        homeBtn.setOpaque(false);
        homeBtn.setOpaque(false);
        homeBtn.setContentAreaFilled( false );
        homeBtn.setBorder( null );
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(homeBtn);
        homeBtn.setBounds(270, 10, 70, 50);

        taskbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Taskbar.png"))); // NOI18N
        taskbar.setText("jLabel2");
        jLayeredPane1.add(taskbar);
        taskbar.setBounds(0, -10, 360, 140);

        jLabel10.setText("57");
        jLayeredPane1.add(jLabel10);
        jLabel10.setBounds(290, 230, 20, 14);

        jLabel11.setText("58");
        jLayeredPane1.add(jLabel11);
        jLabel11.setBounds(290, 290, 20, 14);

        jLabel12.setText("59");
        jLayeredPane1.add(jLabel12);
        jLabel12.setBounds(290, 350, 20, 14);

        jLabel13.setText("60");
        jLayeredPane1.add(jLabel13);
        jLabel13.setBounds(290, 410, 20, 14);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        jLayeredPane1.add(bg);
        bg.setBounds(0, 0, 360, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        Fixtures f = new Fixtures();
        f.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomeScreen h = new HomeScreen();
        h.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quarters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quarters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quarters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quarters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quarters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel date3;
    private javax.swing.JLabel date4;
    private javax.swing.JPanel fixture1;
    private javax.swing.JPanel fixture2;
    private javax.swing.JPanel fixture3;
    private javax.swing.JPanel fixture4;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel matchLbl;
    private javax.swing.JLabel matchLbl2;
    private javax.swing.JLabel matchLbl3;
    private javax.swing.JLabel matchLbl4;
    private javax.swing.JLabel qFinalsLbl;
    private javax.swing.JLabel taskbar;
    private javax.swing.JLabel v1;
    private javax.swing.JLabel v2;
    private javax.swing.JLabel v3;
    private javax.swing.JLabel v4;
    private javax.swing.JLabel venue1;
    private javax.swing.JLabel venue2;
    private javax.swing.JLabel venue3;
    private javax.swing.JLabel venue4;
    private javax.swing.JLabel w49Lbl;
    private javax.swing.JLabel w50Lbl;
    private javax.swing.JLabel w51Lbl;
    private javax.swing.JLabel w52Lbl;
    private javax.swing.JLabel w53Lbl;
    private javax.swing.JLabel w54Lbl;
    private javax.swing.JLabel w55Lbl;
    private javax.swing.JLabel w56Lbl;
    // End of variables declaration//GEN-END:variables
}
