/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package worldcupapp;

/**
 *
 * @author Nathan Ryan x13448212 Group 7
 */
public class Round16 extends javax.swing.JFrame {

    /**
     * Creates new form SecondStage
     */
    public Round16() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        v6 = new javax.swing.JLabel();
        fixture8 = new javax.swing.JPanel();
        venue8 = new javax.swing.JLabel();
        date8 = new javax.swing.JLabel();
        matchLbl6 = new javax.swing.JLabel();
        oneHLbl = new javax.swing.JLabel();
        twoGLbl = new javax.swing.JLabel();
        twoFLbl = new javax.swing.JLabel();
        v5 = new javax.swing.JLabel();
        oneELbl = new javax.swing.JLabel();
        fixture5 = new javax.swing.JPanel();
        venue5 = new javax.swing.JLabel();
        date5 = new javax.swing.JLabel();
        matchLbl5 = new javax.swing.JLabel();
        v4 = new javax.swing.JLabel();
        fixture4 = new javax.swing.JPanel();
        venue4 = new javax.swing.JLabel();
        date4 = new javax.swing.JLabel();
        matchLbl4 = new javax.swing.JLabel();
        oneDLbl = new javax.swing.JLabel();
        twoCLbl = new javax.swing.JLabel();
        oneBLbl = new javax.swing.JLabel();
        v3 = new javax.swing.JLabel();
        fixture3 = new javax.swing.JPanel();
        venue3 = new javax.swing.JLabel();
        date3 = new javax.swing.JLabel();
        matchLbl3 = new javax.swing.JLabel();
        twoALbl = new javax.swing.JLabel();
        oneCLbl = new javax.swing.JLabel();
        v2 = new javax.swing.JLabel();
        fixture2 = new javax.swing.JPanel();
        venue2 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        matchLbl2 = new javax.swing.JLabel();
        twoDLbl = new javax.swing.JLabel();
        v1 = new javax.swing.JLabel();
        fixture1 = new javax.swing.JPanel();
        venue1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        matchLbl = new javax.swing.JLabel();
        oneALbl = new javax.swing.JLabel();
        twoBLbl = new javax.swing.JLabel();
        roundsixteenLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        taskbar = new javax.swing.JLabel();
        fixture9 = new javax.swing.JPanel();
        venue9 = new javax.swing.JLabel();
        date9 = new javax.swing.JLabel();
        matchLbl7 = new javax.swing.JLabel();
        fixture10 = new javax.swing.JPanel();
        venue10 = new javax.swing.JLabel();
        date10 = new javax.swing.JLabel();
        matchLbl8 = new javax.swing.JLabel();
        oneGLBl = new javax.swing.JLabel();
        v7 = new javax.swing.JLabel();
        twoHLbl = new javax.swing.JLabel();
        oneFLbl = new javax.swing.JLabel();
        v8 = new javax.swing.JLabel();
        twoELbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        jLabel3.setText("Match No");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        v6.setText("v");
        jLayeredPane1.add(v6);
        v6.setBounds(130, 560, 6, 14);

        fixture8.setBackground(new java.awt.Color(255, 255, 0));

        venue8.setText("Porto Alegre");

        date8.setText("30/06 17:00");

        matchLbl6.setText("Match No");

        javax.swing.GroupLayout fixture8Layout = new javax.swing.GroupLayout(fixture8);
        fixture8.setLayout(fixture8Layout);
        fixture8Layout.setHorizontalGroup(
            fixture8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date8)
                .addGap(77, 77, 77)
                .addComponent(venue8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(matchLbl6))
        );
        fixture8Layout.setVerticalGroup(
            fixture8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue8)
                    .addComponent(date8)
                    .addComponent(matchLbl6)))
        );

        jLayeredPane1.add(fixture8);
        fixture8.setBounds(20, 410, 300, 14);

        oneHLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oneHLbl.setText("1H");
        jLayeredPane1.add(oneHLbl);
        oneHLbl.setBounds(20, 560, 90, 17);

        twoGLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        twoGLbl.setText("2G");
        jLayeredPane1.add(twoGLbl);
        twoGLbl.setBounds(170, 560, 80, 17);

        twoFLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        twoFLbl.setText("2F");
        jLayeredPane1.add(twoFLbl);
        twoFLbl.setBounds(170, 380, 70, 17);

        v5.setText("v");
        jLayeredPane1.add(v5);
        v5.setBounds(130, 380, 6, 14);

        oneELbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oneELbl.setText("1E");
        jLayeredPane1.add(oneELbl);
        oneELbl.setBounds(20, 380, 100, 17);

        fixture5.setBackground(new java.awt.Color(255, 255, 0));

        venue5.setText("Brasilia");

        date5.setText("30/06 13:00");

        matchLbl5.setText("Match No");

        javax.swing.GroupLayout fixture5Layout = new javax.swing.GroupLayout(fixture5);
        fixture5.setLayout(fixture5Layout);
        fixture5Layout.setHorizontalGroup(
            fixture5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date5)
                .addGap(82, 82, 82)
                .addComponent(venue5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(matchLbl5))
        );
        fixture5Layout.setVerticalGroup(
            fixture5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue5)
                    .addComponent(date5)
                    .addComponent(matchLbl5)))
        );

        jLayeredPane1.add(fixture5);
        fixture5.setBounds(20, 350, 300, 14);

        v4.setText("v");
        jLayeredPane1.add(v4);
        v4.setBounds(130, 320, 6, 14);

        fixture4.setBackground(new java.awt.Color(255, 255, 0));

        venue4.setText("Recife");

        date4.setText("29/06 17:00");

        matchLbl4.setText("Match No");

        javax.swing.GroupLayout fixture4Layout = new javax.swing.GroupLayout(fixture4);
        fixture4.setLayout(fixture4Layout);
        fixture4Layout.setHorizontalGroup(
            fixture4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date4)
                .addGap(77, 77, 77)
                .addComponent(venue4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(matchLbl4))
        );
        fixture4Layout.setVerticalGroup(
            fixture4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue4)
                    .addComponent(date4)
                    .addComponent(matchLbl4)))
        );

        jLayeredPane1.add(fixture4);
        fixture4.setBounds(20, 290, 300, 14);

        oneDLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oneDLbl.setText("1D");
        jLayeredPane1.add(oneDLbl);
        oneDLbl.setBounds(20, 320, 100, 17);

        twoCLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        twoCLbl.setText("2C");
        jLayeredPane1.add(twoCLbl);
        twoCLbl.setBounds(170, 320, 110, 17);

        oneBLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oneBLbl.setText("1B");
        jLayeredPane1.add(oneBLbl);
        oneBLbl.setBounds(20, 260, 70, 17);

        v3.setText("v");
        jLayeredPane1.add(v3);
        v3.setBounds(130, 260, 6, 14);

        fixture3.setBackground(new java.awt.Color(255, 255, 0));

        venue3.setText("Fortaleza");

        date3.setText("29/06 13:00");

        matchLbl3.setText("Match No");

        javax.swing.GroupLayout fixture3Layout = new javax.swing.GroupLayout(fixture3);
        fixture3.setLayout(fixture3Layout);
        fixture3Layout.setHorizontalGroup(
            fixture3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date3)
                .addGap(71, 71, 71)
                .addComponent(venue3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(matchLbl3))
        );
        fixture3Layout.setVerticalGroup(
            fixture3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue3)
                    .addComponent(date3)
                    .addComponent(matchLbl3)))
        );

        jLayeredPane1.add(fixture3);
        fixture3.setBounds(20, 230, 300, 14);

        twoALbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        twoALbl.setText("2A");
        jLayeredPane1.add(twoALbl);
        twoALbl.setBounds(170, 260, 80, 17);

        oneCLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oneCLbl.setText("1C");
        jLayeredPane1.add(oneCLbl);
        oneCLbl.setBounds(20, 200, 80, 17);

        v2.setText("v");
        jLayeredPane1.add(v2);
        v2.setBounds(130, 200, 6, 14);

        fixture2.setBackground(new java.awt.Color(255, 255, 0));

        venue2.setText("Rio De Janeiro");

        date2.setText("28/06 17:00");

        matchLbl2.setText("Match No");

        javax.swing.GroupLayout fixture2Layout = new javax.swing.GroupLayout(fixture2);
        fixture2.setLayout(fixture2Layout);
        fixture2Layout.setHorizontalGroup(
            fixture2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(date2)
                .addGap(60, 60, 60)
                .addComponent(venue2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(matchLbl2))
        );
        fixture2Layout.setVerticalGroup(
            fixture2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue2)
                    .addComponent(date2)
                    .addComponent(matchLbl2)))
        );

        jLayeredPane1.add(fixture2);
        fixture2.setBounds(20, 176, 300, 14);

        twoDLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        twoDLbl.setText("2D");
        jLayeredPane1.add(twoDLbl);
        twoDLbl.setBounds(170, 200, 90, 17);

        v1.setText("v");
        jLayeredPane1.add(v1);
        v1.setBounds(130, 140, 6, 14);

        fixture1.setBackground(new java.awt.Color(255, 255, 0));

        venue1.setText("Belo Horizonte");

        date1.setText("28/06 13:00");

        matchLbl.setText("Match No");

        javax.swing.GroupLayout fixture1Layout = new javax.swing.GroupLayout(fixture1);
        fixture1.setLayout(fixture1Layout);
        fixture1Layout.setHorizontalGroup(
            fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(date1)
                .addGap(63, 63, 63)
                .addComponent(venue1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(matchLbl))
        );
        fixture1Layout.setVerticalGroup(
            fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue1)
                    .addComponent(date1)
                    .addComponent(matchLbl)))
        );

        jLayeredPane1.add(fixture1);
        fixture1.setBounds(20, 110, 300, 14);

        oneALbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oneALbl.setText("1A");
        jLayeredPane1.add(oneALbl);
        oneALbl.setBounds(20, 140, 70, 17);

        twoBLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        twoBLbl.setText("2B");
        jLayeredPane1.add(twoBLbl);
        twoBLbl.setBounds(180, 140, 100, 17);

        roundsixteenLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        roundsixteenLbl.setForeground(new java.awt.Color(255, 255, 255));
        roundsixteenLbl.setText("Round Of 16");
        jLayeredPane1.add(roundsixteenLbl);
        roundsixteenLbl.setBounds(120, 60, 110, 50);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fixtures/back.png"))); // NOI18N
        backBtn.setOpaque(false);
        backBtn.setOpaque(false);
        backBtn.setContentAreaFilled( false );
        backBtn.setBorder( null );
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(backBtn);
        backBtn.setBounds(10, 10, 80, 50);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fixtures/home.png"))); // NOI18N
        homeBtn.setOpaque(false);
        homeBtn.setOpaque(false);
        homeBtn.setContentAreaFilled( false );
        homeBtn.setBorder( null );
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(homeBtn);
        homeBtn.setBounds(270, 10, 70, 50);

        taskbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Taskbar.png"))); // NOI18N
        taskbar.setText("jLabel2");
        jLayeredPane1.add(taskbar);
        taskbar.setBounds(0, -10, 360, 140);

        fixture9.setBackground(new java.awt.Color(255, 255, 0));

        venue9.setText("Sao Paulo");

        date9.setText("01/07 13:00");

        matchLbl7.setText("Match No");

        javax.swing.GroupLayout fixture9Layout = new javax.swing.GroupLayout(fixture9);
        fixture9.setLayout(fixture9Layout);
        fixture9Layout.setHorizontalGroup(
            fixture9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date9)
                .addGap(78, 78, 78)
                .addComponent(venue9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(matchLbl7))
        );
        fixture9Layout.setVerticalGroup(
            fixture9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue9)
                    .addComponent(date9)
                    .addComponent(matchLbl7)))
        );

        jLayeredPane1.add(fixture9);
        fixture9.setBounds(20, 470, 300, 14);

        fixture10.setBackground(new java.awt.Color(255, 255, 0));

        venue10.setText("Salvador");

        date10.setText("01/07 17:00");

        matchLbl8.setText("Match No");

        javax.swing.GroupLayout fixture10Layout = new javax.swing.GroupLayout(fixture10);
        fixture10.setLayout(fixture10Layout);
        fixture10Layout.setHorizontalGroup(
            fixture10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date10)
                .addGap(76, 76, 76)
                .addComponent(venue10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(matchLbl8))
        );
        fixture10Layout.setVerticalGroup(
            fixture10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue10)
                    .addComponent(date10)
                    .addComponent(matchLbl8)))
        );

        jLayeredPane1.add(fixture10);
        fixture10.setBounds(20, 530, 300, 14);

        oneGLBl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oneGLBl.setText("1G");
        jLayeredPane1.add(oneGLBl);
        oneGLBl.setBounds(20, 440, 90, 17);

        v7.setText("v");
        jLayeredPane1.add(v7);
        v7.setBounds(130, 440, 6, 14);

        twoHLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        twoHLbl.setText("2H");
        jLayeredPane1.add(twoHLbl);
        twoHLbl.setBounds(170, 440, 80, 17);

        oneFLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oneFLbl.setText("1F");
        jLayeredPane1.add(oneFLbl);
        oneFLbl.setBounds(20, 500, 90, 17);

        v8.setText("v");
        jLayeredPane1.add(v8);
        v8.setBounds(130, 500, 6, 14);

        twoELbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        twoELbl.setText("2E");
        jLayeredPane1.add(twoELbl);
        twoELbl.setBounds(170, 500, 80, 17);

        jLabel10.setText("49");
        jLayeredPane1.add(jLabel10);
        jLabel10.setBounds(280, 140, 20, 14);

        jLabel11.setText("50");
        jLayeredPane1.add(jLabel11);
        jLabel11.setBounds(280, 200, 20, 14);

        jLabel12.setText("51");
        jLayeredPane1.add(jLabel12);
        jLabel12.setBounds(280, 260, 20, 14);

        jLabel13.setText("52");
        jLayeredPane1.add(jLabel13);
        jLabel13.setBounds(280, 320, 20, 14);

        jLabel14.setText("53");
        jLayeredPane1.add(jLabel14);
        jLabel14.setBounds(280, 380, 20, 14);

        jLabel15.setText("54");
        jLayeredPane1.add(jLabel15);
        jLabel15.setBounds(280, 440, 20, 14);

        jLabel16.setText("55");
        jLayeredPane1.add(jLabel16);
        jLabel16.setBounds(280, 500, 20, 14);

        jLabel17.setText("56");
        jLayeredPane1.add(jLabel17);
        jLabel17.setBounds(280, 560, 20, 14);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        jLayeredPane1.add(bg);
        bg.setBounds(0, 0, 360, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        Fixtures f = new Fixtures();
        f.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomeScreen h = new HomeScreen();
        h.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Round16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Round16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Round16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Round16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Round16().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date10;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel date3;
    private javax.swing.JLabel date4;
    private javax.swing.JLabel date5;
    private javax.swing.JLabel date8;
    private javax.swing.JLabel date9;
    private javax.swing.JPanel fixture1;
    private javax.swing.JPanel fixture10;
    private javax.swing.JPanel fixture2;
    private javax.swing.JPanel fixture3;
    private javax.swing.JPanel fixture4;
    private javax.swing.JPanel fixture5;
    private javax.swing.JPanel fixture8;
    private javax.swing.JPanel fixture9;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel matchLbl;
    private javax.swing.JLabel matchLbl2;
    private javax.swing.JLabel matchLbl3;
    private javax.swing.JLabel matchLbl4;
    private javax.swing.JLabel matchLbl5;
    private javax.swing.JLabel matchLbl6;
    private javax.swing.JLabel matchLbl7;
    private javax.swing.JLabel matchLbl8;
    private javax.swing.JLabel oneALbl;
    private javax.swing.JLabel oneBLbl;
    private javax.swing.JLabel oneCLbl;
    private javax.swing.JLabel oneDLbl;
    private javax.swing.JLabel oneELbl;
    private javax.swing.JLabel oneFLbl;
    private javax.swing.JLabel oneGLBl;
    private javax.swing.JLabel oneHLbl;
    private javax.swing.JLabel roundsixteenLbl;
    private javax.swing.JLabel taskbar;
    private javax.swing.JLabel twoALbl;
    private javax.swing.JLabel twoBLbl;
    private javax.swing.JLabel twoCLbl;
    private javax.swing.JLabel twoDLbl;
    private javax.swing.JLabel twoELbl;
    private javax.swing.JLabel twoFLbl;
    private javax.swing.JLabel twoGLbl;
    private javax.swing.JLabel twoHLbl;
    private javax.swing.JLabel v1;
    private javax.swing.JLabel v2;
    private javax.swing.JLabel v3;
    private javax.swing.JLabel v4;
    private javax.swing.JLabel v5;
    private javax.swing.JLabel v6;
    private javax.swing.JLabel v7;
    private javax.swing.JLabel v8;
    private javax.swing.JLabel venue1;
    private javax.swing.JLabel venue10;
    private javax.swing.JLabel venue2;
    private javax.swing.JLabel venue3;
    private javax.swing.JLabel venue4;
    private javax.swing.JLabel venue5;
    private javax.swing.JLabel venue8;
    private javax.swing.JLabel venue9;
    // End of variables declaration//GEN-END:variables
}
