/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package worldcupapp;

import javax.swing.JOptionPane;

/**
 *
 * @author x13323161
 */
public class Standings extends javax.swing.JFrame {
    
    //Variables
    String search, Team, odds;
    
    //array
    CupOdds[] arr;
    
    //counter
    
    int count;
    

    /**
     * Creates new form Standings
     */
    public Standings() {
        initComponents();
         arr = new CupOdds[100];
         count = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        InfoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        GroupA = new javax.swing.JPanel();
        A = new javax.swing.JLabel();
        GroupB = new javax.swing.JPanel();
        B = new javax.swing.JLabel();
        GroupC = new javax.swing.JPanel();
        C = new javax.swing.JLabel();
        GroupD = new javax.swing.JPanel();
        D = new javax.swing.JLabel();
        GroupE = new javax.swing.JPanel();
        E = new javax.swing.JLabel();
        GroupF = new javax.swing.JPanel();
        F = new javax.swing.JLabel();
        GroupG = new javax.swing.JPanel();
        G = new javax.swing.JLabel();
        GroupH = new javax.swing.JPanel();
        H = new javax.swing.JLabel();
        Belgium = new javax.swing.JLabel();
        Algeria = new javax.swing.JLabel();
        Russia = new javax.swing.JLabel();
        Korea = new javax.swing.JLabel();
        Germany = new javax.swing.JLabel();
        Portugal = new javax.swing.JLabel();
        Ghana = new javax.swing.JLabel();
        USA = new javax.swing.JLabel();
        Argentina = new javax.swing.JLabel();
        Bosnia = new javax.swing.JLabel();
        Iran = new javax.swing.JLabel();
        Nigeria = new javax.swing.JLabel();
        Switzerland = new javax.swing.JLabel();
        Ecuador = new javax.swing.JLabel();
        France = new javax.swing.JLabel();
        Honduras = new javax.swing.JLabel();
        Uruguay = new javax.swing.JLabel();
        CostaRica = new javax.swing.JLabel();
        England = new javax.swing.JLabel();
        Italy = new javax.swing.JLabel();
        Columbia = new javax.swing.JLabel();
        Greece = new javax.swing.JLabel();
        Cote = new javax.swing.JLabel();
        Japan = new javax.swing.JLabel();
        Spain = new javax.swing.JLabel();
        Netherlands = new javax.swing.JLabel();
        Chile = new javax.swing.JLabel();
        Australia = new javax.swing.JLabel();
        Brazil = new javax.swing.JLabel();
        Croatia = new javax.swing.JLabel();
        Mexico = new javax.swing.JLabel();
        Cameroon = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        Odds = new javax.swing.JButton();
        TopBar = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 880));

        InfoPanel.setBackground(new java.awt.Color(255, 255, 0));
        InfoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Gp.");

        jLabel2.setText("Goals");

        jLabel3.setText("Diff.");

        jLabel4.setText("Pt.");

        javax.swing.GroupLayout InfoPanelLayout = new javax.swing.GroupLayout(InfoPanel);
        InfoPanel.setLayout(InfoPanelLayout);
        InfoPanelLayout.setHorizontalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPanelLayout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addGap(12, 12, 12))
        );
        InfoPanelLayout.setVerticalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jLabel2)
                .addComponent(jLabel3)
                .addComponent(jLabel4))
        );

        GroupA.setBackground(new java.awt.Color(0, 0, 0));

        A.setForeground(new java.awt.Color(255, 255, 255));
        A.setText("Group A");

        javax.swing.GroupLayout GroupALayout = new javax.swing.GroupLayout(GroupA);
        GroupA.setLayout(GroupALayout);
        GroupALayout.setHorizontalGroup(
            GroupALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GroupALayout.createSequentialGroup()
                .addComponent(A)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        GroupALayout.setVerticalGroup(
            GroupALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GroupALayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(A))
        );

        GroupB.setBackground(new java.awt.Color(0, 0, 0));

        B.setForeground(new java.awt.Color(255, 255, 255));
        B.setText("Group B");

        javax.swing.GroupLayout GroupBLayout = new javax.swing.GroupLayout(GroupB);
        GroupB.setLayout(GroupBLayout);
        GroupBLayout.setHorizontalGroup(
            GroupBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GroupBLayout.createSequentialGroup()
                .addComponent(B)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        GroupBLayout.setVerticalGroup(
            GroupBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B)
        );

        GroupC.setBackground(new java.awt.Color(0, 0, 0));

        C.setForeground(new java.awt.Color(255, 255, 255));
        C.setText("Group C");

        javax.swing.GroupLayout GroupCLayout = new javax.swing.GroupLayout(GroupC);
        GroupC.setLayout(GroupCLayout);
        GroupCLayout.setHorizontalGroup(
            GroupCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GroupCLayout.createSequentialGroup()
                .addComponent(C)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        GroupCLayout.setVerticalGroup(
            GroupCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(C)
        );

        GroupD.setBackground(new java.awt.Color(0, 0, 0));

        D.setForeground(new java.awt.Color(255, 255, 255));
        D.setText("Group D");

        javax.swing.GroupLayout GroupDLayout = new javax.swing.GroupLayout(GroupD);
        GroupD.setLayout(GroupDLayout);
        GroupDLayout.setHorizontalGroup(
            GroupDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GroupDLayout.createSequentialGroup()
                .addComponent(D)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        GroupDLayout.setVerticalGroup(
            GroupDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(D)
        );

        GroupE.setBackground(new java.awt.Color(0, 0, 0));

        E.setForeground(new java.awt.Color(255, 255, 255));
        E.setText("Group E");

        javax.swing.GroupLayout GroupELayout = new javax.swing.GroupLayout(GroupE);
        GroupE.setLayout(GroupELayout);
        GroupELayout.setHorizontalGroup(
            GroupELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GroupELayout.createSequentialGroup()
                .addComponent(E)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        GroupELayout.setVerticalGroup(
            GroupELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GroupELayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(E))
        );

        GroupF.setBackground(new java.awt.Color(0, 0, 0));

        F.setForeground(new java.awt.Color(255, 255, 255));
        F.setText("Group F");

        javax.swing.GroupLayout GroupFLayout = new javax.swing.GroupLayout(GroupF);
        GroupF.setLayout(GroupFLayout);
        GroupFLayout.setHorizontalGroup(
            GroupFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GroupFLayout.createSequentialGroup()
                .addComponent(F)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        GroupFLayout.setVerticalGroup(
            GroupFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(F)
        );

        GroupG.setBackground(new java.awt.Color(0, 0, 0));

        G.setForeground(new java.awt.Color(255, 255, 255));
        G.setText("Group G");

        javax.swing.GroupLayout GroupGLayout = new javax.swing.GroupLayout(GroupG);
        GroupG.setLayout(GroupGLayout);
        GroupGLayout.setHorizontalGroup(
            GroupGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GroupGLayout.createSequentialGroup()
                .addComponent(G)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        GroupGLayout.setVerticalGroup(
            GroupGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(G)
        );

        GroupH.setBackground(new java.awt.Color(0, 0, 0));

        H.setForeground(new java.awt.Color(255, 255, 255));
        H.setText("Group H");

        javax.swing.GroupLayout GroupHLayout = new javax.swing.GroupLayout(GroupH);
        GroupH.setLayout(GroupHLayout);
        GroupHLayout.setHorizontalGroup(
            GroupHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GroupHLayout.createSequentialGroup()
                .addComponent(H)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        GroupHLayout.setVerticalGroup(
            GroupHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(H)
        );

        Belgium.setText("Belgium");

        Algeria.setText("Algeria");

        Russia.setText("Russia");

        Korea.setText("Korea Republic");

        Germany.setText("Germany");

        Portugal.setText("Portugal");

        Ghana.setText("Ghana");

        USA.setText("USA");

        Argentina.setText("Argentina");

        Bosnia.setText("Bosnia");

        Iran.setText("Iran");

        Nigeria.setText("Nigeria");

        Switzerland.setText("Switzerland");

        Ecuador.setText("Ecuador");

        France.setText("France");

        Honduras.setText("Honduras");

        Uruguay.setText("Uruguay");

        CostaRica.setText("Costa Rica");

        England.setText("England");

        Italy.setText("Italy");

        Columbia.setText("Columbia");

        Greece.setText("Greece");

        Cote.setText("Côte d'Ivoire");

        Japan.setText("Japan");

        Spain.setText("Spain");

        Netherlands.setText("Netherlands");

        Chile.setText("Chile");

        Australia.setText("Australia");

        Brazil.setText("Brazil");

        Croatia.setText("Croatia");

        Mexico.setText("Mexico");

        Cameroon.setText("Cameroon");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(InfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GroupA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GroupB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GroupC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GroupD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GroupE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GroupF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GroupG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GroupH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Belgium)
                    .addComponent(Algeria)
                    .addComponent(Russia)
                    .addComponent(Korea)
                    .addComponent(Germany)
                    .addComponent(Portugal)
                    .addComponent(USA)
                    .addComponent(Ghana)
                    .addComponent(Argentina)
                    .addComponent(Bosnia)
                    .addComponent(Iran)
                    .addComponent(Nigeria)
                    .addComponent(Switzerland)
                    .addComponent(Ecuador)
                    .addComponent(France)
                    .addComponent(Honduras)
                    .addComponent(Uruguay)
                    .addComponent(CostaRica)
                    .addComponent(England)
                    .addComponent(Italy)
                    .addComponent(Columbia)
                    .addComponent(Greece)
                    .addComponent(Cote)
                    .addComponent(Japan)
                    .addComponent(Spain)
                    .addComponent(Netherlands)
                    .addComponent(Chile)
                    .addComponent(Australia)
                    .addComponent(Brazil)
                    .addComponent(Croatia)
                    .addComponent(Mexico)
                    .addComponent(Cameroon))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GroupA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(Brazil)
                .addGap(5, 5, 5)
                .addComponent(Croatia)
                .addGap(5, 5, 5)
                .addComponent(Mexico)
                .addGap(5, 5, 5)
                .addComponent(Cameroon)
                .addGap(5, 5, 5)
                .addComponent(GroupB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(Spain)
                .addGap(5, 5, 5)
                .addComponent(Netherlands)
                .addGap(5, 5, 5)
                .addComponent(Chile)
                .addGap(5, 5, 5)
                .addComponent(Australia)
                .addGap(5, 5, 5)
                .addComponent(GroupC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(Columbia)
                .addGap(5, 5, 5)
                .addComponent(Greece)
                .addGap(5, 5, 5)
                .addComponent(Cote)
                .addGap(5, 5, 5)
                .addComponent(Japan)
                .addGap(5, 5, 5)
                .addComponent(GroupD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(Uruguay)
                .addGap(5, 5, 5)
                .addComponent(CostaRica)
                .addGap(5, 5, 5)
                .addComponent(England)
                .addGap(5, 5, 5)
                .addComponent(Italy)
                .addGap(5, 5, 5)
                .addComponent(GroupE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(Switzerland)
                .addGap(5, 5, 5)
                .addComponent(Ecuador)
                .addGap(5, 5, 5)
                .addComponent(France)
                .addGap(5, 5, 5)
                .addComponent(Honduras)
                .addGap(5, 5, 5)
                .addComponent(GroupF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(Argentina)
                .addGap(5, 5, 5)
                .addComponent(Bosnia)
                .addGap(5, 5, 5)
                .addComponent(Iran)
                .addGap(5, 5, 5)
                .addComponent(Nigeria)
                .addGap(5, 5, 5)
                .addComponent(GroupG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(Germany)
                .addGap(5, 5, 5)
                .addComponent(Portugal)
                .addGap(5, 5, 5)
                .addComponent(Ghana)
                .addGap(5, 5, 5)
                .addComponent(USA)
                .addGap(5, 5, 5)
                .addComponent(GroupH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(Belgium)
                .addGap(5, 5, 5)
                .addComponent(Algeria)
                .addGap(5, 5, 5)
                .addComponent(Russia)
                .addGap(5, 5, 5)
                .addComponent(Korea)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);
        jScrollPane1.getViewport().setOpaque(false);

        jLayeredPane1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 340, 510);
        jScrollPane1.getViewport().setOpaque(false);

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standings/home.png"))); // NOI18N
        Home.setOpaque(false);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Home);
        Home.setBounds(300, 10, 50, 50);
        Home.setOpaque(false);
        Home.setContentAreaFilled( false );
        Home.setBorder( null );

        Odds.setText("Odds Checker");
        Odds.setOpaque(false);
        Odds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OddsActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Odds);
        Odds.setBounds(110, 70, 130, 23);

        TopBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standings/Taskbar.png"))); // NOI18N
        jLayeredPane1.add(TopBar);
        TopBar.setBounds(0, 0, 360, 120);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/standings/bg.png"))); // NOI18N
        jLayeredPane1.add(Background);
        Background.setBounds(0, 0, 360, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OddsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OddsActionPerformed
        // TODO add your handling code here:
        
        String search = JOptionPane.showInputDialog(null,"Enter team name");
        
        CupOdds co;
        co = new CupOdds();
        
        if(search.equalsIgnoreCase("Brazil")){
            co.setname("Brazil belongs in Group A");
            co.setodds(" 3/1 ");
            
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
            
        }else if (search.equalsIgnoreCase("Mexico")){
            co.setTeam("Mexico belongs in Group A");
            co.setOdds(" 125/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
        }else if (search.equalsIgnoreCase("Croatia")){
            co.setTeam("Croatia belongs in Group A");
            co.setOdds(" 125/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
            
         }else if (search.equalsIgnoreCase("Cameroon")){
            co.setTeam("Cameroon belongs in Group A");
            co.setOdds(" 500/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
           }else if (search.equalsIgnoreCase("Netherlands")){
            co.setTeam("Netherlands belongs in Group B");
            co.setOdds(" 100/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
         }else if (search.equalsIgnoreCase("Holland")){
            co.setTeam("Holland belongs in Group B");
            co.setOdds(" 25/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
         }else if (search.equalsIgnoreCase("Spain")){
            co.setTeam("Spain belongs in Group B");
            co.setOdds(" 7/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
         }else if (search.equalsIgnoreCase("Chile")){
            co.setTeam("Chile belongs in Group B");
            co.setOdds(" 40/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
         }else if (search.equalsIgnoreCase("Australia")){
            co.setTeam("Australia belongs in Group B");
            co.setOdds(" 500/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
         }else if (search.equalsIgnoreCase("Columbia")){
            co.setTeam("Columbia belongs in Group C");
            co.setOdds(" 25/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
          }else if (search.equalsIgnoreCase("Greece")){
            co.setTeam("Greece belongs in Group C");
            co.setOdds(" 200/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
          }else if (search.equalsIgnoreCase("Ivory Coast")){
            co.setTeam("Ivory Coast belongs in Group C");
            co.setOdds(" 100/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
          }else if (search.equalsIgnoreCase("Japan")){
            co.setTeam("Japan belongs in Group C");
            co.setOdds(" 150/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
          }else if (search.equalsIgnoreCase("Uruguay")){
            co.setTeam("Uruguay belongs in Group D");
            co.setOdds(" 25/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
          }else if (search.equalsIgnoreCase("Costa Rica")){
            co.setTeam("Costa Rica belongs in Group D");
            co.setOdds(" 2000/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
          }else if (search.equalsIgnoreCase("England")){
            co.setTeam("England belongs in Group D");
            co.setOdds(" 33/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
          }else if (search.equalsIgnoreCase("Italy")){
            co.setTeam("Italy belongs in Group D");
            co.setOdds(" 25/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
          }else if (search.equalsIgnoreCase("Switzerland")){
            co.setTeam("Switzerland belongs in Group E");
            co.setOdds(" 100/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
         }else if (search.equalsIgnoreCase("Ecuador")){
            co.setTeam("Ecuador belongs in Group E");
            co.setOdds(" 125/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
         }else if (search.equalsIgnoreCase("France")){
            co.setTeam("France belongs in Group E");
            co.setOdds(" 20/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
         }else if (search.equalsIgnoreCase("Honduras")){
            co.setTeam("Honduras belongs in Group E");
            co.setOdds(" 150/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
         }else if (search.equalsIgnoreCase("Argentina")){
            co.setTeam("Argentina belongs in Group F");
            co.setOdds(" 5/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
           }else if (search.equalsIgnoreCase("Bosnia")){
            co.setTeam("Bosnia belongs in Group F");
            co.setOdds(" 150/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
           }else if (search.equalsIgnoreCase("Iran")){
            co.setTeam("Iran belongs in Group F");
            co.setOdds(" 1500/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
           }else if (search.equalsIgnoreCase("Nigeria")){
            co.setTeam("Nigeria belongs in Group F");
            co.setOdds(" 200/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
           }else if (search.equalsIgnoreCase("Germany")){
            co.setTeam("Germany belongs in Group G");
            co.setOdds(" 11/2 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
         }else if (search.equalsIgnoreCase("Portugal")){
            co.setTeam("Portugal belongs in Group G");
            co.setOdds(" 33/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
         }else if (search.equalsIgnoreCase("Ghana")){
            co.setTeam("Ghana belongs in Group G");
            co.setOdds(" 150/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
         }else if (search.equalsIgnoreCase("USA")){
            co.setTeam("USA belongs in Group G");
            co.setOdds(" 150/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
         }else if (search.equalsIgnoreCase("Belgium")){
            co.setTeam("Belgium belongs in Group H");
            co.setOdds(" 150/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
          }else if (search.equalsIgnoreCase("Algeria")){
            co.setTeam("Algeria belongs in Group H");
            co.setOdds(" 2000/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
          }else if (search.equalsIgnoreCase("Russia")){
            co.setTeam("Russia belongs in Group H");
            co.setOdds(" 66/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
          }else if (search.equalsIgnoreCase("South Korea")){
            co.setTeam("South Korea belongs in Group H");
            co.setOdds(" 300/1 ");
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam() + "\n " + co.getOdds() + "\n ");
         
          }else if (search.equalsIgnoreCase("Ireland")){
            co.setTeam("Ireland didn't qualify this year!");
            
        
            arr[count] = co;
            count++;
            
         JOptionPane.showMessageDialog(null, " " + co.getTeam());
         
         } else {
            JOptionPane.showMessageDialog(null, "This is not a valid search term");
        }
    }//GEN-LAST:event_OddsActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        HomeScreen h = new HomeScreen();
        h.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Standings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Standings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Standings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Standings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Standings().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel Algeria;
    private javax.swing.JLabel Argentina;
    private javax.swing.JLabel Australia;
    private javax.swing.JLabel B;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Belgium;
    private javax.swing.JLabel Bosnia;
    private javax.swing.JLabel Brazil;
    private javax.swing.JLabel C;
    private javax.swing.JLabel Cameroon;
    private javax.swing.JLabel Chile;
    private javax.swing.JLabel Columbia;
    private javax.swing.JLabel CostaRica;
    private javax.swing.JLabel Cote;
    private javax.swing.JLabel Croatia;
    private javax.swing.JLabel D;
    private javax.swing.JLabel E;
    private javax.swing.JLabel Ecuador;
    private javax.swing.JLabel England;
    private javax.swing.JLabel F;
    private javax.swing.JLabel France;
    private javax.swing.JLabel G;
    private javax.swing.JLabel Germany;
    private javax.swing.JLabel Ghana;
    private javax.swing.JLabel Greece;
    private javax.swing.JPanel GroupA;
    private javax.swing.JPanel GroupB;
    private javax.swing.JPanel GroupC;
    private javax.swing.JPanel GroupD;
    private javax.swing.JPanel GroupE;
    private javax.swing.JPanel GroupF;
    private javax.swing.JPanel GroupG;
    private javax.swing.JPanel GroupH;
    private javax.swing.JLabel H;
    private javax.swing.JButton Home;
    private javax.swing.JLabel Honduras;
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JLabel Iran;
    private javax.swing.JLabel Italy;
    private javax.swing.JLabel Japan;
    private javax.swing.JLabel Korea;
    private javax.swing.JLabel Mexico;
    private javax.swing.JLabel Netherlands;
    private javax.swing.JLabel Nigeria;
    private javax.swing.JButton Odds;
    private javax.swing.JLabel Portugal;
    private javax.swing.JLabel Russia;
    private javax.swing.JLabel Spain;
    private javax.swing.JLabel Switzerland;
    private javax.swing.JLabel TopBar;
    private javax.swing.JLabel USA;
    private javax.swing.JLabel Uruguay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
