/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package worldcupapp;

import javax.swing.UIManager;

/**
 *
 * @author Jefferson x13452702
 */
public class TeamPage extends javax.swing.JFrame {

    //variables
    String des;
    //declare array of objects
    teamDes[] arr;
    //declare counter
    int count;

    /**
     * Creates new form TeamPage
     */
    public TeamPage() {
        initComponents();

        //create array
        arr = new teamDes[100];
        //initialise count to 0
        count = 0;

        UIManager.put("TabbedPane.contentOpaque", false);




        // elements of an ArrayList



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        back = new javax.swing.JButton();
        Home1 = new javax.swing.JButton();
        tab = new javax.swing.JTabbedPane();
        CountryList = new javax.swing.JScrollPane();
        CL = new javax.swing.JPanel();
        Algeria = new javax.swing.JButton();
        Argentina = new javax.swing.JButton();
        Australia = new javax.swing.JButton();
        Belgium = new javax.swing.JButton();
        Bosnia = new javax.swing.JButton();
        Brazil = new javax.swing.JButton();
        Cameroon = new javax.swing.JButton();
        Chile = new javax.swing.JButton();
        Colombia = new javax.swing.JButton();
        Costa = new javax.swing.JButton();
        Cote = new javax.swing.JButton();
        Croatia = new javax.swing.JButton();
        England = new javax.swing.JButton();
        Ecuador = new javax.swing.JButton();
        France = new javax.swing.JButton();
        Germany = new javax.swing.JButton();
        Ghana = new javax.swing.JButton();
        Greece = new javax.swing.JButton();
        Honduras = new javax.swing.JButton();
        Iran = new javax.swing.JButton();
        Italy = new javax.swing.JButton();
        Japan = new javax.swing.JButton();
        Korea = new javax.swing.JButton();
        Mexico = new javax.swing.JButton();
        NetherLands = new javax.swing.JButton();
        Nigeria = new javax.swing.JButton();
        Portugal = new javax.swing.JButton();
        Rusia = new javax.swing.JButton();
        Spain = new javax.swing.JButton();
        Switzerland = new javax.swing.JButton();
        Uruguay = new javax.swing.JButton();
        USA = new javax.swing.JButton();
        CountryInfo = new javax.swing.JScrollPane();
        CI = new javax.swing.JPanel();
        Ppic = new javax.swing.JLabel();
        coachTeam = new javax.swing.JLabel();
        Region = new javax.swing.JLabel();
        Group = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Team Information");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(0, 60, 360, 50);

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/search.png"))); // NOI18N
        search.setToolTipText("");
        search.setVisible(false);
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.setOpaque(false);
        search.setContentAreaFilled( false );
        search.setBorder( null );
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jLayeredPane1.add(search);
        search.setBounds(250, 10, 40, 40);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/back.png"))); // NOI18N
        back.setToolTipText("");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.setVisible(false);
        back.setOpaque(false);
        back.setContentAreaFilled( false );
        back.setBorder( null );
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jLayeredPane1.add(back);
        back.setBounds(20, 20, 40, 40);

        Home1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/home.png"))); // NOI18N
        Home1.setToolTipText("");
        Home1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home1.setOpaque(false);
        Home1.setContentAreaFilled( false );
        Home1.setBorder( null );
        Home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Home1);
        Home1.setBounds(300, 10, 50, 50);

        tab.setOpaque(false);

        CountryList.setBorder(null);
        CountryList.setOpaque(false);
        CountryList.setPreferredSize(new java.awt.Dimension(300, 2500));
        CountryList.getViewport().setOpaque(false);

        CL.setOpaque(false);
        CL.setPreferredSize(new java.awt.Dimension(300, 2450));

        Algeria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/algeriabutt.png"))); // NOI18N
        Algeria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Algeria.setOpaque(false);
        Algeria.setContentAreaFilled( false );
        Algeria.setBorder( null );
        Algeria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlgeriaActionPerformed(evt);
            }
        });

        Argentina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/argentina.png"))); // NOI18N
        Argentina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Argentina.setOpaque(false);
        Argentina.setContentAreaFilled( false );
        Argentina.setBorder( null );
        Argentina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArgentinaActionPerformed(evt);
            }
        });

        Australia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/aus.png"))); // NOI18N
        Australia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Australia.setOpaque(false);
        Australia.setContentAreaFilled( false );
        Australia.setBorder( null );
        Australia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AustraliaActionPerformed(evt);
            }
        });

        Belgium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/bel.png"))); // NOI18N
        Belgium.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Belgium.setOpaque(false);
        Belgium.setContentAreaFilled( false );
        Belgium.setBorder( null );
        Belgium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BelgiumActionPerformed(evt);
            }
        });

        Bosnia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/bosnia.png"))); // NOI18N
        Bosnia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bosnia.setOpaque(false);
        Bosnia.setContentAreaFilled( false );
        Bosnia.setBorder( null );
        Bosnia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BosniaActionPerformed(evt);
            }
        });

        Brazil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/bRAZIL.png"))); // NOI18N
        Brazil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Brazil.setOpaque(false);
        Brazil.setContentAreaFilled( false );
        Brazil.setBorder( null );
        Brazil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrazilActionPerformed(evt);
            }
        });

        Cameroon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/CAMEROON.png"))); // NOI18N
        Cameroon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cameroon.setOpaque(false);
        Cameroon.setContentAreaFilled( false );
        Cameroon.setBorder( null );
        Cameroon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CameroonActionPerformed(evt);
            }
        });

        Chile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/chile.png"))); // NOI18N
        Chile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chile.setOpaque(false);
        Chile.setContentAreaFilled( false );
        Chile.setBorder( null );
        Chile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChileActionPerformed(evt);
            }
        });

        Colombia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/colombia.png"))); // NOI18N
        Colombia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Colombia.setOpaque(false);
        Colombia.setContentAreaFilled( false );
        Colombia.setBorder( null );
        Colombia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColombiaActionPerformed(evt);
            }
        });

        Costa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/costa.png"))); // NOI18N
        Costa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Costa.setOpaque(false);
        Costa.setContentAreaFilled( false );
        Costa.setBorder( null );
        Costa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostaActionPerformed(evt);
            }
        });

        Cote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/COTE.png"))); // NOI18N
        Cote.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cote.setOpaque(false);
        Cote.setContentAreaFilled( false );
        Cote.setBorder( null );
        Cote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoteActionPerformed(evt);
            }
        });

        Croatia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/CROATIA.png"))); // NOI18N
        Croatia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Croatia.setOpaque(false);
        Croatia.setContentAreaFilled( false );
        Croatia.setBorder( null );
        Croatia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CroatiaActionPerformed(evt);
            }
        });

        England.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/ENG.png"))); // NOI18N
        England.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        England.setOpaque(false);
        England.setContentAreaFilled( false );
        England.setBorder( null );
        England.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnglandActionPerformed(evt);
            }
        });

        Ecuador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/EQA.png"))); // NOI18N
        Ecuador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ecuador.setOpaque(false);
        Ecuador.setContentAreaFilled( false );
        Ecuador.setBorder( null );
        Ecuador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EcuadorActionPerformed(evt);
            }
        });

        France.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/FRA.png"))); // NOI18N
        France.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        France.setOpaque(false);
        France.setContentAreaFilled( false );
        France.setBorder( null );
        France.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FranceActionPerformed(evt);
            }
        });

        Germany.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/GER.png"))); // NOI18N
        Germany.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Germany.setOpaque(false);
        Germany.setContentAreaFilled( false );
        Germany.setBorder( null );
        Germany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GermanyActionPerformed(evt);
            }
        });

        Ghana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/GHAM.png"))); // NOI18N
        Ghana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ghana.setOpaque(false);
        Ghana.setContentAreaFilled( false );
        Ghana.setBorder( null );
        Ghana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GhanaActionPerformed(evt);
            }
        });

        Greece.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/GREECE.png"))); // NOI18N
        Greece.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Greece.setOpaque(false);
        Greece.setContentAreaFilled( false );
        Greece.setBorder( null );
        Greece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreeceActionPerformed(evt);
            }
        });

        Honduras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/HON.png"))); // NOI18N
        Honduras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Honduras.setOpaque(false);
        Honduras.setContentAreaFilled( false );
        Honduras.setBorder( null );
        Honduras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HondurasActionPerformed(evt);
            }
        });

        Iran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/IRAN.png"))); // NOI18N
        Iran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Iran.setOpaque(false);
        Iran.setContentAreaFilled( false );
        Iran.setBorder( null );
        Iran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IranActionPerformed(evt);
            }
        });

        Italy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/ITAL.png"))); // NOI18N
        Italy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Italy.setOpaque(false);
        Italy.setContentAreaFilled( false );
        Italy.setBorder( null );
        Italy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItalyActionPerformed(evt);
            }
        });

        Japan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/JAPAN.png"))); // NOI18N
        Japan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Japan.setOpaque(false);
        Japan.setContentAreaFilled( false );
        Japan.setBorder( null );
        Japan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JapanActionPerformed(evt);
            }
        });

        Korea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/KOREA.png"))); // NOI18N
        Korea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Korea.setOpaque(false);
        Korea.setContentAreaFilled( false );
        Korea.setBorder( null );
        Korea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KoreaActionPerformed(evt);
            }
        });

        Mexico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/MEXICO.png"))); // NOI18N
        Mexico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mexico.setOpaque(false);
        Mexico.setContentAreaFilled( false );
        Mexico.setBorder( null );
        Mexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MexicoActionPerformed(evt);
            }
        });

        NetherLands.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/NETHER.png"))); // NOI18N
        NetherLands.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NetherLands.setOpaque(false);
        NetherLands.setContentAreaFilled( false );
        NetherLands.setBorder( null );
        NetherLands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NetherLandsActionPerformed(evt);
            }
        });

        Nigeria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/NIGIRA.png"))); // NOI18N
        Nigeria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Nigeria.setOpaque(false);
        Nigeria.setContentAreaFilled( false );
        Nigeria.setBorder( null );
        Nigeria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NigeriaActionPerformed(evt);
            }
        });

        Portugal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/PORTUGAL.png"))); // NOI18N
        Portugal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Portugal.setOpaque(false);
        Portugal.setContentAreaFilled( false );
        Portugal.setBorder( null );
        Portugal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PortugalActionPerformed(evt);
            }
        });

        Rusia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RUSSIA.png"))); // NOI18N
        Rusia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Rusia.setOpaque(false);
        Rusia.setContentAreaFilled( false );
        Rusia.setBorder( null );
        Rusia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RusiaActionPerformed(evt);
            }
        });

        Spain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/SPAIN.png"))); // NOI18N
        Spain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Spain.setOpaque(false);
        Spain.setContentAreaFilled( false );
        Spain.setBorder( null );
        Spain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpainActionPerformed(evt);
            }
        });

        Switzerland.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/SWIZ.png"))); // NOI18N
        Switzerland.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Switzerland.setOpaque(false);
        Switzerland.setContentAreaFilled( false );
        Switzerland.setBorder( null );
        Switzerland.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwitzerlandActionPerformed(evt);
            }
        });

        Uruguay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/URUG.png"))); // NOI18N
        Uruguay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Uruguay.setOpaque(false);
        Uruguay.setContentAreaFilled( false );
        Uruguay.setBorder( null );
        Uruguay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UruguayActionPerformed(evt);
            }
        });

        USA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/USA.png"))); // NOI18N
        USA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        USA.setOpaque(false);
        USA.setContentAreaFilled( false );
        USA.setBorder( null );
        USA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CLLayout = new javax.swing.GroupLayout(CL);
        CL.setLayout(CLLayout);
        CLLayout.setHorizontalGroup(
            CLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(CLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Cote, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(England, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(France, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Honduras, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Italy, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Korea, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Portugal, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spain, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Uruguay, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nigeria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rusia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Switzerland, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(USA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(NetherLands, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Greece, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Iran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Japan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mexico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Ghana, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Costa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Croatia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ecuador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Germany, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Colombia, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Argentina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Australia, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Belgium, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Bosnia, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Brazil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cameroon, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Chile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(Algeria, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        CLLayout.setVerticalGroup(
            CLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Algeria, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Argentina, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Australia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Belgium, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bosnia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Brazil, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cameroon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Chile, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Colombia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Costa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cote, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Croatia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(England, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ecuador, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(France, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Germany, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ghana, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Greece, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Honduras, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Iran, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Italy, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Japan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(Korea, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mexico, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NetherLands, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nigeria, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Portugal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rusia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Spain, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Switzerland, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Uruguay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(USA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(335, Short.MAX_VALUE))
        );

        CountryList.setViewportView(CL);

        tab.addTab("", CountryList);

        CountryInfo.setHorizontalScrollBar(null);
        CountryInfo.setOpaque(false);
        CountryInfo.getViewport().setOpaque(false);

        CI.setOpaque(false);

        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/alg.png"))); // NOI18N

        javax.swing.GroupLayout CILayout = new javax.swing.GroupLayout(CI);
        CI.setLayout(CILayout);
        CILayout.setHorizontalGroup(
            CILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CILayout.createSequentialGroup()
                        .addComponent(Ppic, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(CILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Region, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(coachTeam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Group, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(text1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                .addContainerGap())
        );
        CILayout.setVerticalGroup(
            CILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CILayout.createSequentialGroup()
                        .addComponent(coachTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Region, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Group, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Ppic, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2017, Short.MAX_VALUE))
        );

        CountryInfo.setViewportView(CI);

        tab.addTab("", CountryInfo);

        jLayeredPane1.add(tab);
        tab.setBounds(0, 110, 360, 520);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Taskbar.png"))); // NOI18N
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(0, 0, 360, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/bg.png"))); // NOI18N
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(0, 0, 360, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        back.setVisible(false);
        CountryList.setVisible(true);
        CountryInfo.setVisible(false);
        search.setVisible(false);
        CL.setVisible(true);
        CI.setVisible(false);
        jLabel3.setText("Team Information");

    }//GEN-LAST:event_backActionPerformed

    private void Home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home1ActionPerformed
        HomeScreen h = new HomeScreen();
        h.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_Home1ActionPerformed

    private void USAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USAActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        CountryInfo.setVisible(true);
        search.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("United States");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/usa.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Oscar W. Tabarez");
        Region.setText("Region: North America");
        Group.setText("Group: G");
        teamDes td;

        td = new teamDes();
        td.setDes("<html> USA is based in Group G <br/><br/> The first US team to turn up at a FIFA world finals earned the dubious nickname of the ‘shot-putters’ for their muscular and burly nature, but 3-0 wins over Paraguay and Belgium in 1930 was enough for a third-place finish, to this day the best placing for any team outside of Europe or South America. Four years later the Americans went out in the first round, but they caused a grand sensation in Brazil in 1950 when, led by outstanding goalkeeper Frank Borghi, they managed to beat mighty England in Belo Horizante in an upsets for the ages. Another first-round exit came in 1990, but as hosts in 1994 they managed to reach the knockout rounds, a result that paved the way to more consistency. And after a last-place finish at France 1998, they beat Portugal and Mexico in Korea/Japan 2002 and only just missed out on a semi-final place after losing to Germany. In 2006 they went out in the first round again, this time in Germany before reaching the Round of 16 in South Africa in 2010.</html>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_USAActionPerformed

    private void UruguayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UruguayActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        search.setVisible(true);
        CountryInfo.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Uruguay");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/uru.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Oscar W. Tabarez");
        Region.setText("Region: South America");
        Group.setText("Group: D");
        teamDes td;

        td = new teamDes();
        td.setDes("<html> Uruguay is based in Group D<br/><br/> Prior to the 1970s, when they began a lengthy period in the doldrums, Uruguay were widely regarded as one of the giants of world football. That status was founded on their two FIFA World Cup™ wins, the first of them coming at home in 1930 and the second in Brazil 20 years later, when they stunned the host nation with a shock 2-1 win at the Maracana, an epoch-defining game that will forever be known as El Maracanazo. Their run to the semi-finals at Mexico 1970 would be their last flourish for some considerable time.</html>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_UruguayActionPerformed

    private void SwitzerlandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwitzerlandActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        CountryInfo.setVisible(true);
        search.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Switzerland");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/swiz.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Ottmar Hitzfeld");
        Region.setText("Region: Europe");
        Group.setText("Group: E");
        teamDes td;

        td = new teamDes();
        td.setDes("<html> Switzerland is based in Group E <br/><br/> Switzerland have contested the FIFA World Cup finals nine times to date (1934, 1938, 1950, 1954, 1962, 1966, 1994, 2006 and 2010), reaching the last eight on three occasions. However, their most recent appearance at the quarter-final stage came almost 50 years ago, at the 1954 finals on home soil. <br/><br/>Since then, the Swiss have twice made the last sixteen (1994 and 2006), but failed to survive the group stage three times. Their group campaign in 2010 was a bittersweet affair: they handed eventual world champions Spain a 1-0 defeat in their opening fixture, but ultimately packed for home after just three games.</hmtl>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_SwitzerlandActionPerformed

    private void SpainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpainActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        search.setVisible(true);
        CountryInfo.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Spain");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/spa.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Vicente Del Bosque");
        Region.setText("Region: Europs");
        Group.setText("Group: B");
        teamDes td;

        td = new teamDes();
        td.setDes("<html> Spain is based in Group B <br/><br/>Prior to lifting the coveted Trophy in South Africa, so frequent were their exits at the last eight of the finals that Spain were said to be suffering from a ‘quarter-final jinx’. Brazil 2014 will be La Selección's tenth consecutive world finals appearance, and 14th in all, with their best performance before last year’s success coming at Brazil 1950. Having topped their first-round section, Spain went straight into the decisive four-team final group stage – where they finished fourth behind Uruguay, Brazil and Sweden. </html>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_SpainActionPerformed

    private void RusiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RusiaActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        CountryInfo.setVisible(true);
        search.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Russia");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/russ.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        coachTeam.setText("Coach: Fabio Capello");
        Region.setText("Region: Europe");
        Group.setText("Group: H");
        teamDes td;

        td = new teamDes();
        td.setDes("<hmtl> Russia is based in Group H <br/><br/> Russia reached the quarter-finals at Sweden 1958, Chile 1962 and Mexico 1970. In the former two tournaments, they were eliminated by the hosts, while Uruguay were accountable for their exit after extra time in Mexico City. The Eastern Europeans went one better at England 1966, when, inspired by goalkeeper Lev Yashin and forward Igor Chislenko, they topped their group and edged a formidable Hungary, before losing 2-1 to both West Germany in the semis and Portugal in the play-off for third place.</html>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_RusiaActionPerformed

    private void PortugalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PortugalActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        CountryInfo.setVisible(true);
        search.setVisible(false);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Portugal");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/por.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Paulo Bento");
        Region.setText("Region: Europe");
        Group.setText("Group: G");
        teamDes td;

        td = new teamDes();
        td.setDes("<html>Portugal is based in Group G <br/><br/> It was not until England 1966 that the Portuguese made their world finals debut, yet as entrances go it could hardly have been more impressive. Spearheaded by the irrepressible Eusebio, Portugal’s golden generation knocked out Brazil en route to the semi-finals, where they came up just short against the host nation. Consolation came in the shape of victory over the Soviet Union in the match for third place. The Portuguese do not have happy memories of their next appearance on the big stage, however, which came at Mexico 1986. Despite opening up with a win over England, they went out in the group phase after defeats to Poland and Morocco. </html>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_PortugalActionPerformed

    private void NigeriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NigeriaActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        CountryInfo.setVisible(true);
        search.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Nigeria");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/nigeria.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Stephen Keshi");
        Region.setText("Region: Africa");
        Group.setText("Group: F");
        teamDes td;

        td = new teamDes();
        td.setDes("<html>Nigeria is based in Group F<br/><br/> After impressing on their way to the second round in each of their first two FIFA World Cup appearances, 1994 and 1998, Nigeria have struggled since: going out at the group stage three times while taking just two points from their last eight matches in the finals. A muddled South Africa 2010 campaign under Lars Lagerback did little to bolster Nigeria’s reputation, but Brazil 2014 offers another chance for the reigning African champions to soar.</html>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_NigeriaActionPerformed

    private void NetherLandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NetherLandsActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        CountryInfo.setVisible(true);
        search.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Netherlands");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/ne.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Louis Van Gaal");
        Region.setText("Region: Europe");
        Group.setText("Group: B");
        teamDes td;

        td = new teamDes();
        td.setDes("<html> Netherlands is based in Group B <br/><br/> With legendary coach Rinus Michels pulling the strings from the bench, Johan Cruyff, Johan Neeskens and Co won their way through to the Final in 1974, only to lose out to the hosts. Four years on, their revolutionary Total Football again took them to the showpiece, but history repeated itself as they suffered another defeat to the host nation, succumbing 3-1 in Buenos Aires. The Oranje then experienced Final heartbreak for a third time in Johannesburg, coming within four minutes of taking Spain to penalties before Andres Iniesta crushed their dreams.</html>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_NetherLandsActionPerformed

    private void MexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MexicoActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        CountryInfo.setVisible(true);
        search.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Mexico");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/me.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Miguel Herrera");
        Region.setText("Region: North America");
        Group.setText("Group: A");
        teamDes td;

        td = new teamDes();
        td.setDes("<html> Mexico is based in Group A <br/><br/> Mexico have fallen in the Round of 16 on their last five appearances in the finals, with Argentina halting their progress at both Germany 2006 and South Africa 2010. Those defeats proved painful for El Tri’s legion of fans, who have been waiting a long time to see their side return to last eight. Only twice have the Mexicans made it to the quarters, both time on home soil, in 1970 and 1986.</hmtl>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_MexicoActionPerformed

    private void KoreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KoreaActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        search.setVisible(true);
        CountryInfo.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("South Korea");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/sk.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Hong Myungbo");
        Region.setText("Region: Asia");
        Group.setText("Group: H");
        teamDes td;

        td = new teamDes();
        td.setDes("<hrml> Korea is based in Group H <br/><br/> Despite being Asia’s most frequent visitors to world football’s showpiece event, Korea Republic had never won a match at the finals until they co-hosted Korea/Japan 2002. They got off to a winning start with victory over Poland before defeating Portugal to reach the second round for the first time. The Taeguk Warriors went on to reach the semi-finals at the expense of Italy and Spain, only to lose to Germany in the last four. In 2010, they made history again by reaching the knockout stage for the first time on foreign soil, before going down at the hands of Uruguay in the Round of 16.</html>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_KoreaActionPerformed

    private void JapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JapanActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        search.setVisible(true);
        CountryInfo.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Japan");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/jp.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Alberto Zaccheroni");
        Region.setText("Region: Japan");
        Group.setText("Group: C");
        teamDes td;
        td = new teamDes();
        td.setDes("<html> Japan is based in Group C <br/><br/> They failed to live up to the expectations in their debut FIFA World Cup, losing three straight games to bow out. However, 2002 Korea/Japan saw them make history on home soil in Asia's first FIFA World Cup, winning a group that also featured Russia, Belgium and Tunisia to storm into the second round, only to lose out to eventual third-place finishers Turkey by a solitary goal. They were brought back down to earth at Germany 2006, salvaging merely a point from three group games to dump out.<br/><br/> They more than redeemed themselves at South Africa 2010 though, progressing to the second stage at the expense of the likes of Denmark and Cameroon. They came close to stunning Paraguay in the consequent round-of-16 clash, with the South Americans only advancing through a penalty shootout victory after regular and extra time finished goalless. </html>");
        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_JapanActionPerformed

    private void ItalyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItalyActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        CountryInfo.setVisible(true);
        search.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Italy");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/ita.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Cesare Prandelli");
        Region.setText("Region: Europe");
        Group.setText("Group: D");
        teamDes td;

        td = new teamDes();
        td.setDes("<html> Italy is based in Group D <br/><br/> With four world titles to their name (1934, 1938, 1982 and 2006) and two runners-up slots (1970 and 1994), Italy lie second only to Brazil on the all-time FIFA World Cup honours board. La Squadra Azzurra are also the only team along with the Brazilians to have won the competition twice in a row. Their 4-3 semi-final defeat of West Germany at Mexico 1970 is widely regarded as one of the most spectacular matches in the history of the tournament.</html> ");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_ItalyActionPerformed

    private void IranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IranActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        CountryInfo.setVisible(true);
        search.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Iran");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/ira.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Carlos Queiroz");
        Region.setText("Region: Asia");
        Group.setText("Group: F");
        teamDes td;

        td = new teamDes();
        td.setDes("<hmtl> Iran is based in Group F <br/><br/> Despite their presence within Asia, Iran have so far been unable to progress beyond the group phase at the FIFA World Cup. They finished their debut campaign with a point, courtesy of a 1-1 draw against Scotland. But their first win came in the second appearance when a golden generation, boasting the likes of Ali Daei, Karim Bagheri and Mehdi Mahdavikia, came up with a memorable 2-1 defeat of USA. Their last participation at Germany 2006 saw them head home with a point after a 1-1 draw against debutants Angola. </html>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_IranActionPerformed

    private void HondurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HondurasActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        CountryInfo.setVisible(true);
        search.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Honduras");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/hon.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Luis F. Suarez");
        Region.setText("Region: North America");
        Group.setText("Group: E");
        teamDes td;

        td = new teamDes();
        td.setDes("<hmtl> Honduras is based in Group E <br/><br/> Upon making their first FIFA World Cup return in nearly three decades, Honduras were faced with tough group adversaries in South Africa, including eventual World Champions Spain. The Hondurans opened the tournament with a 1-0 loss to Chile, and soon became the ill-fated team to first encounter the wrath of tournament top-scorer David Villa, who grabbed both goals in Spain’s 2-0 win. In their only other FIFA World Cup appearance, Jose de La Paz held the coaching reins and steered Honduras to a surprising opening 1-1 draw with Spain, the 1982 tournament’s hosts, and followed up that account with the same scoreline against Northern Ireland. Their campaign was cut short, however, at the group stage after Yugoslavia beat Los Catrachos 1-0 thanks to a late goal. </html>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_HondurasActionPerformed

    private void GreeceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreeceActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        CountryInfo.setVisible(true);
        search.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Greece");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/gre.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Fernando Santos");
        Region.setText("Region: Europe");
        Group.setText("Group: C");
        teamDes td;

        td = new teamDes();
        td.setDes("<html> Greece is based in Group C<br/><br/> The undoubted high point in Greek footballing history was their stunning triumph at EURO 2004 in Portugal, but their record at the FIFA World Cup finals is distinctly modest. At USA 1994, they departed for home with no points and no goals following group stage defeats to Argentina (4-0), Bulgaria (4-0) and Nigeria (2-0). Some 16 years later, the trip to South Africa did produce a 2-1 win over Nigeria, but 2-0 defeats to Korea Republic and Argentina meant another group stage exit.</html>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_GreeceActionPerformed

    private void GhanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GhanaActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        CountryInfo.setVisible(true);
        CL.setVisible(false);
        search.setVisible(true);
        CI.setVisible(true);
        jLabel3.setText("Ghana");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/gha.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Kwesi Appiah");
        Region.setText("Region: Africa");
        Group.setText("Group: G");
        teamDes td;

        td = new teamDes();
        td.setDes("<html> Ghana is based in Group G <br/><br/> An impressive FIFA World Cup finals in 2006 saw the Black Stars beat the Czech Republic and the USA before being eliminated by Brazil in the second round, but they were the only African team to escape their group. In 2010, they were again the only side from the continent in the knockout rounds, and they equalled Africa’s best-ever performance by beating the USA to reach the quarter-finals. Ghana’s loss in a penalty kick shoot-out to Uruguay in the last eight was perhaps the most dramatic of the tournament, and they may well consider themselves as having unfinished business after Asamoah Gyan’s missed penalty kick denied them from becoming the first African side to reach the semi-finals of a FIFA World Cup. </hmtl>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_GhanaActionPerformed

    private void GermanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GermanyActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        CountryInfo.setVisible(true);
        CL.setVisible(false);
        search.setVisible(true);
        CI.setVisible(true);
        jLabel3.setText("Germany");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/ger.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Joachim Low");
        Region.setText("Region: Europe");
        Group.setText("Group: G");
        teamDes td;

        td = new teamDes();
        td.setDes("<html> Germany is based in Group G <br/><br/> Germany lie third in the all-time world football ranking with three FIFA World Cup triumphs, behind only Brazil on five and Italy on four. The 1954 team won the tournament in Switzerland as rank outsiders, in what became known as the Miracle of Berne. Franz Beckenbauer lifted the trophy on home soil in 1974, and Lothar Matthaus followed suit at Italy 1990.\n" +
"\n"+"The Germans have also finished runners-up four times, in 1966, 1982, 1986 and 2002, and came third on four occasions, in 1934 and 1970, and at the last two finals in 2006 and 2010. No other team has played more matches (99) or scored more goals (222) at the FIFA World Cup finals.</html>");
        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_GermanyActionPerformed

    private void FranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FranceActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        CountryInfo.setVisible(true);
        search.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("France");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/fra.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Didier Deschamps");
        Region.setText("Region: Europe");
        Group.setText("Group: E");
        teamDes td;

        td = new teamDes();
        td.setDes("<html> France is based in Group E <br/><br/> France have always commanded respect on the global stage thanks to various legendary players and impressive performances dating back to 1930, but they made the leap to a whole new level in 1998. Whereas Platini, Alain Giresse, Jean Tigana and Co experienced agony at the semi-final stage in 1982 and 1986, the likes of Zinedine Zidane, Laurent Blanc and Didier Deschamps finally took Les Bleus all the way, lifting the Trophy on home soil. That was followed by a surprise group-stage exit four years later, but they came close to adding a second star to their shirts in 2006, only losing out on penalties to Italy in the Final. Without 'Zizou' in their ranks, France then made a forgettable tilt at South Africa 2010, disappointing their supporters both on and off the pitch.</html> ");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_FranceActionPerformed

    private void EcuadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EcuadorActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        search.setVisible(true);
        CountryInfo.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Ecuador");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/ecu.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Reinaldo Rueda");
        Region.setText("Region: South America");
        Group.setText("Group: E");
        teamDes td;

        td = new teamDes();
        td.setDes(" <html> Ecuador is based in Group E <br/><br/> While Ecuador failed to extricate themselves from a tough group at Korea/Japan 2002, their first-ever appearance at the final stages of a FIFA World Cup, the story was quite different at Germany 2006, where the South Americans got as far as the last 16, having surprisingly finished second in their pool behind the host nation. Unfortunately for the CONMEBOL representatives, England would prove a hurdle too far; the Three Lions triumphed 1-0 to move on to the quarter-finals.</html>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_EcuadorActionPerformed

    private void EnglandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnglandActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        search.setVisible(true);
        CountryInfo.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("England");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/eng.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Roy Hodson");
        Region.setText("Region: Europe");
        Group.setText("Group: D");
        teamDes td;

        td = new teamDes();
        td.setDes("<html> Enland is based in Group D <br/><br/>England have appeared at 13 editions of the FIFA World Cup, including seven of the last eight. They were below-par at South Africa in 2010, narrowly qualifying from their group with a victory in the final match against Slovenia, before being outclassed 4-1 by Joachim Low’s Germany at the Round of 16 stage. The Three Lions have been FIFA World Cup winners once, in 1966 when they were hosts, but have since suffered a succession of early exits. Sir Bobby Robson came closest to matching the achievements of Sir Alf Ramsey’s ‘Wingless Wonders’, guiding England to the semi-finals at Italy 1990 only to be knocked out on penalties by Germany. </html>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_EnglandActionPerformed

    private void CroatiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CroatiaActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        search.setVisible(true);
        CountryInfo.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Croatia");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/cro.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Niko Kovac");
        Region.setText("Region: Europe");
        Group.setText("Group: A");
        teamDes td;
        td = new teamDes();
        td.setDes("<html>Croatia is based in Group A <br/><br/> The Croats arrived for their maiden shot at the FIFA World Cup™ in 1998 as virtual unknowns, but were to prove one of the surprises of the tournament. They finished second in their group behind Argentina after losing 1-0 to the South Americans, but beating Jamaica 3-1 and Japan 1-0. A 1-0 win over Romania saw them through to the last eight and a meeting with Germany, where they stunningly won 3-0 to send the three-time world champions packing. Hosts and eventual winners France proved too strong in a 2-1 semi-final defeat, but the new boys crowned a dream debut by beating the Netherlands 2-1 in the third place play-off. The next two tournaments proved thoroughly disappointing by comparison, as Croatia failed to survive the group stage at both Korea/Japan 2002 and Germany 2006.</html>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());

    }//GEN-LAST:event_CroatiaActionPerformed

    private void CoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoteActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        search.setVisible(true);
        CountryInfo.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Cote d'ivoire");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/cote.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Sabri Lamouchi");
        Region.setText("Region: Africa");
        Group.setText("Group: C");
        teamDes td;

        td = new teamDes();
        td.setDes("<html> Cote d'ivoire is based in Group C <br/><br/> Côte d’Ivoire have never made it past the group stage of a FIFA World Cup finals, but it is perhaps worth pointing out that the draw has never been particularly kind to them. For their debut appearance in 2006, the Elephants shared Group C with Argentina, Netherlands and Serbia and Montenegro. They finished third in the pool, just as they did in South Africa four years later, when they were drawn alongside Brazil, Portugal and Korea DPR. </html>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_CoteActionPerformed

    private void CostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostaActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        search.setVisible(true);
        CountryInfo.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Costa Rica");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/costarica.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Jorge Luis Pinto");
        Region.setText("Region: North America");
        Group.setText("Group: D");
        teamDes td;

        td = new teamDes();
        td.setDes("<html> Costa Rica is based in Group D <br/><br/> Costa Rica played their first game as a national team in 1921, a 7-0 win over Central American neighbours El Salvador. As they developed as a side, things weren’t always quite so easy, but after many years of manful efforts they finally managed to reach the world’s biggest football tournament in 1990, taking full advantage of Mexico’s suspension to reach the finals in Italy. Once there, they beat Sweden and Scotland to reach the knockout rounds in an impressive debut under the care of wily boss Bora Milutinovic, where they lost to Czechoslovakia.\n" +
"\n" +
"They returned to the world stage in 2002 after narrowly failing to reach USA 1994 and France 1998. Drawn into a tricky group alongside eventual champions Brazil and semi-finalists Turkey, the valiant Ticos went out at the first hurdle, the same stage where they would make their exit in a significantly poorer showing four years later in Germany. </html>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_CostaActionPerformed

    private void ColombiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColombiaActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        search.setVisible(true);
        CountryInfo.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Colombia");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/colombia.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Jose Pekerman");
        Region.setText("Region: South America");
        Group.setText("Group: C");
        teamDes td;

        td = new teamDes();
        td.setDes("<html> Colombia is based in Group C <br/><br/> With the exception of Italy 1990, when the golden generation that included Rene Higuita and Carlos Valderrama slipped up against unfancied Cameroon in the Round of 16, Colombia have never made it past the group stage at the FIFA World Cup. In fact, an analysis of the other three campaigns reveals a disappointing combined record of six defeats, one draw and just two wins at the tournament. </html>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_ColombiaActionPerformed

    private void ChileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChileActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        search.setVisible(true);
        CountryInfo.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Chile");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/chile.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Jorge Sampaoli");
        Region.setText("Region: South America");
        Group.setText("Group: B");
        teamDes td;

        td = new teamDes();
        td.setDes("<html> Chile is based in Group B <br/><br/> With eight FIFA World Cups™ under their belts, Chile are level with Paraguay in fourth place on the list of South American nations that have appeared at most editions of the showpiece event. Their best performance to date came when finishing third as host nation in 1962. On five other occasions they have failed to progress from the group phase, while at France 1998 and South Africa 2010 they reached the Round of 16, only to exit at the hands of Brazil on both occasions. </html>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_ChileActionPerformed

    private void CameroonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CameroonActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        search.setVisible(true);
        CountryInfo.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Cameroon");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/cam.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Volker Finke");
        Region.setText("Region: Africa");
        Group.setText("Group: A");
        teamDes td;

        td = new teamDes();
        td.setDes("<html>Cameroon is based in Group A <br/><br/> Perhaps no team has done more to shake up perceptions of African football. The Indomitable Lions exited Spain 1982 at the group stage, but they ended their maiden excursion undefeated, having drawn 0-0 with both Peru and Poland and 1-1 with eventual winners Italy. Eight years later, they wrote themselves into the annals of the game by beating holders Argentina in the Opening Match and becoming the first African side to reach the quarter-finals, powered by the goals of evergreen striker Roger Milla. That breakthrough performance remains their finest showing, group-stage exits having followed in 1994, 1998, 2002 and 2010.</html>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_CameroonActionPerformed

    private void BrazilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrazilActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        search.setVisible(true);
        CountryInfo.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Brazil");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/bra.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Luiz Felipe Scolari");
        Region.setText("Region: South America");
        Group.setText("Group: A");
        teamDes td;

        td = new teamDes();
        td.setDes("<html> Brazil is based in Group A <br/><br/> So demanding are the Brazilian faithful, even a Seleção squad that finishes runners-up at a FIFA World Cup finals cannot be sure what kind of reception they will get on their return home. The only nation to have taken part in every edition of the elite competition, Brazil have lifted the coveted Trophy on a record five occasions (1958, 1962, 1970, 1994 and 2002), finished in second place twice (1950 and 1998) and taken the last spot on the podium at another two editions (1938 and 1978).</html>");


        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_BrazilActionPerformed

    private void BosniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BosniaActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        search.setVisible(true);
        CountryInfo.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Bosnia");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/bos.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Safet Susic");
        Region.setText("Region: Europe");
        Group.setText("Group: F");
        teamDes td;
        td = new teamDes();
        td.setDes("<html>Bosnia is based in Group F <br/><br/> Bosnia-Herzegovina had an outstanding campaign, winning eight of their ten matches, drawing and losing just once. A ruthless attack and resilient rearguard were the cornerstones of the side’s success, with the 30 goals scored representing the fourth-highest tally in European zone qualifying. Equally impressive was a defence that was breached just six times. Bosnia-Herzegovina’s notable goal difference proved crucial too, edging them past a Greece side that finished level on points, to secure direct passage to Brazil 2014 and a first appearance at a FIFA World Cup™. </html>");
        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_BosniaActionPerformed

    private void BelgiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BelgiumActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        search.setVisible(true);
        CountryInfo.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Belgium");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/bel.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Marc Wilmots");
        Region.setText("Region: Europe");
        Group.setText("Group: H");
        teamDes td;
        td = new teamDes();
        td.setDes("<html>Belguim is based in Group H<br/><br/> Founding members of FIFA, Belgium have taken part in 11 FIFA World Cup™ final tournaments and were an ever-present force between 1982 and 2002. In 1998, the side coached by Georges Leekens in his first spell at the helm came third in their group and made an early exit, while in 2002 Robert Waseige’s men fell in the last 16 to eventual winners Brazil. Neither of those teams came anywhere close to matching the generation that sparkled during Mexico 1986, when they reached the semi-finals before succumbing to Argentina.</html>");

        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_BelgiumActionPerformed

    private void AustraliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AustraliaActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        CountryList.setVisible(false);
        search.setVisible(true);
        CountryInfo.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        //changes the label text 
        jLabel3.setText("Australia");
        //sets the  icon for the label 
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/aus.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Ange Postecoglou");
        Region.setText("Region: Asia");
        Group.setText("Group: B");
        teamDes td;
        td = new teamDes();
        td.setDes("<html>Australia is based in Group B <br/><br/> Though a team made up entirely of amateurs secured a scoreless draw against Chile, Australia departed from the 1974 FIFA World Cup without a goal to show from their inaugural appearance. The Socceroos made up for lost time at Germany 2006 and qualified for the Round of 16 before narrowly falling to eventual champions Italy. The German theme continued at South Africa 2010 although this time Australia suffered a 4-0 loss against the European giants in a scoreline which ultimately scuppered their progress. A ten-man 1-1 draw against Ghana and a 2-1 win against Serbia saw the Aussies eliminated on goal difference, three goals off the Africans.</html> ");

        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_AustraliaActionPerformed

    private void ArgentinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArgentinaActionPerformed
        // TODO add your handling code here:
        back.setVisible(true);
        search.setVisible(true);
        CountryList.setVisible(false);
        CountryInfo.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Argentina");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/arg.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Alejandro Sabella");
        Region.setText("Region: South America ");
        Group.setText("Group: F");
        teamDes td;
        td = new teamDes();
        td.setDes("<html> Argentina is based in Group A <br/><br/> Argentina have contested four FIFA World Cup Finals in all, the first of them at the inaugural tournament, Uruguay 1930, when they went down 4-2 to the host nation. Respective contributions from Mario Kempes and Diego Maradona inspired them to the biggest prize in football on home soil in 1978 and again at Mexico 1986, while their last showpiece appearance came at Italy 1990, when they were denied by an Andreas Brehme penalty. Since then they have been unable to progress beyond the quarter-finals.</html>");

        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_ArgentinaActionPerformed

    private void AlgeriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlgeriaActionPerformed
        // TODO add your handling code here:

        back.setVisible(true);
        search.setVisible(true);
        CountryList.setVisible(false);
        CountryInfo.setVisible(true);
        CL.setVisible(false);
        CI.setVisible(true);
        jLabel3.setText("Algeria");
        Ppic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Profile/alg.png"))); // NOI18N
        Ppic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coachTeam.setText("Coach: Vahid Halilhodzic");
        Region.setText("Region: Africa ");
        Group.setText("Group: H");
        teamDes td;
        td = new teamDes();
        //Used a HTML tag so that the text wraps insides the JLabel  
        td.setDes("<html>Algeria is in group H <br/><br/>"  + "\n" + "\nAlgeria have played in a total of three FIFA World Cup finals. They got off to the best possible start at the 1982 edition in Spain, beating West Germany 2-1 in their opening game. Despite a 3-2 victory over Chile in their final group game, an earlier 2-0 loss to Austria meant that while level on points with the latter, they were eliminated on goal difference. Mexico 1986 was less memorable for the north African side. Drawn in Group D with Brazil, Spain and Northern Ireland, two defeats and a draw left them bottom of the table and on the first flight home. Nor were things much better at South Africa 2010. Pitted against England, USA and Slovenia, they lost twice and drew their other fixture, departing the competition without a goal to their name.</html>");
        // Append each string from ArrayList to the end of text in JTextArea
        // separated by newline
        //text.append(td + System.getProperty("line.separator"));
        text1.setText(td.getDes());
    }//GEN-LAST:event_AlgeriaActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        CountryAl algeria = new CountryAl();
        algeria.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeamPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeamPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeamPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeamPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeamPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Algeria;
    private javax.swing.JButton Argentina;
    private javax.swing.JButton Australia;
    private javax.swing.JButton Belgium;
    private javax.swing.JButton Bosnia;
    private javax.swing.JButton Brazil;
    private javax.swing.JPanel CI;
    private javax.swing.JPanel CL;
    private javax.swing.JButton Cameroon;
    private javax.swing.JButton Chile;
    private javax.swing.JButton Colombia;
    private javax.swing.JButton Costa;
    private javax.swing.JButton Cote;
    private javax.swing.JScrollPane CountryInfo;
    private javax.swing.JScrollPane CountryList;
    private javax.swing.JButton Croatia;
    private javax.swing.JButton Ecuador;
    private javax.swing.JButton England;
    private javax.swing.JButton France;
    private javax.swing.JButton Germany;
    private javax.swing.JButton Ghana;
    private javax.swing.JButton Greece;
    private javax.swing.JLabel Group;
    private javax.swing.JButton Home1;
    private javax.swing.JButton Honduras;
    private javax.swing.JButton Iran;
    private javax.swing.JButton Italy;
    private javax.swing.JButton Japan;
    private javax.swing.JButton Korea;
    private javax.swing.JButton Mexico;
    private javax.swing.JButton NetherLands;
    private javax.swing.JButton Nigeria;
    private javax.swing.JButton Portugal;
    private javax.swing.JLabel Ppic;
    private javax.swing.JLabel Region;
    private javax.swing.JButton Rusia;
    private javax.swing.JButton Spain;
    private javax.swing.JButton Switzerland;
    private javax.swing.JButton USA;
    private javax.swing.JButton Uruguay;
    private javax.swing.JButton back;
    private javax.swing.JLabel coachTeam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton search;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JLabel text1;
    // End of variables declaration//GEN-END:variables
}
