/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package worldcupapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Nathan Ryan x13448212 Group 7
 */
public class WCFinal extends javax.swing.JFrame {

    private String TeamInput;

    //declare array of Question objects
    private ArrayList<TeamSearch> qList;
    //declare count variable to keep track of how many objects are in array
    private int count;

    /**
     * Creates new form Final
     */
    public WCFinal() {
        initComponents();

        TeamInput = new String();

        //create array of question objects
        qList = new ArrayList<TeamSearch>();
        //initialise count to 0
        count = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        v1 = new javax.swing.JLabel();
        fixture1 = new javax.swing.JPanel();
        venue1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        matchLbl = new javax.swing.JLabel();
        w61Lbl = new javax.swing.JLabel();
        w62Lbl = new javax.swing.JLabel();
        finalLbl = new javax.swing.JLabel();
        cupLbl = new javax.swing.JLabel();
        backBtn2 = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        taskbar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        questionTf = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        questionLbl = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        v1.setText("v");
        jLayeredPane1.add(v1);
        v1.setBounds(150, 170, 6, 14);

        fixture1.setBackground(new java.awt.Color(255, 255, 0));

        venue1.setText("Rio De Janeiro");

        date1.setText("13/07 16:00");

        matchLbl.setText("Match No");

        javax.swing.GroupLayout fixture1Layout = new javax.swing.GroupLayout(fixture1);
        fixture1.setLayout(fixture1Layout);
        fixture1Layout.setHorizontalGroup(
            fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(date1)
                .addGap(63, 63, 63)
                .addComponent(venue1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(matchLbl))
        );
        fixture1Layout.setVerticalGroup(
            fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fixture1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fixture1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venue1)
                    .addComponent(date1)
                    .addComponent(matchLbl)))
        );

        jLayeredPane1.add(fixture1);
        fixture1.setBounds(30, 140, 300, 14);

        w61Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        w61Lbl.setText("W61");
        jLayeredPane1.add(w61Lbl);
        w61Lbl.setBounds(40, 170, 70, 17);

        w62Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        w62Lbl.setText("W62");
        jLayeredPane1.add(w62Lbl);
        w62Lbl.setBounds(200, 170, 100, 17);

        finalLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        finalLbl.setForeground(new java.awt.Color(255, 255, 255));
        finalLbl.setText("World Cup Final");
        jLayeredPane1.add(finalLbl);
        finalLbl.setBounds(100, 60, 160, 50);

        cupLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cup.png"))); // NOI18N
        jLayeredPane1.add(cupLbl);
        cupLbl.setBounds(40, 220, 256, 256);

        backBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fixtures/back.png"))); // NOI18N
        backBtn2.setOpaque(false);
        backBtn2.setOpaque(false);
        backBtn2.setContentAreaFilled( false );
        backBtn2.setBorder( null );
        backBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(backBtn2);
        backBtn2.setBounds(10, 10, 80, 50);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fixtures/home.png"))); // NOI18N
        homeBtn.setOpaque(false);
        homeBtn.setOpaque(false);
        homeBtn.setContentAreaFilled( false );
        homeBtn.setBorder( null );
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(homeBtn);
        homeBtn.setBounds(270, 10, 70, 50);

        taskbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Taskbar.png"))); // NOI18N
        taskbar.setText("jLabel2");
        jLayeredPane1.add(taskbar);
        taskbar.setBounds(0, -10, 360, 140);

        jLabel10.setText("64");
        jLayeredPane1.add(jLabel10);
        jLabel10.setBounds(300, 170, 30, 14);
        jLayeredPane1.add(questionTf);
        questionTf.setBounds(250, 500, 100, 20);

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(addBtn);
        addBtn.setBounds(190, 550, 70, 23);

        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(viewBtn);
        viewBtn.setBounds(275, 550, 70, 23);

        saveBtn.setText("Save your Selection");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(saveBtn);
        saveBtn.setBounds(190, 580, 160, 23);

        questionLbl.setText("Who do you think will win the World Cup ?");
        jLayeredPane1.add(questionLbl);
        questionLbl.setBounds(10, 500, 240, 20);

        deleteBtn.setText("Delete your Selection");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(deleteBtn);
        deleteBtn.setBounds(190, 610, 160, 23);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        jLayeredPane1.add(bg);
        bg.setBounds(0, 0, 360, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn2ActionPerformed
        Fixtures f = new Fixtures();
        f.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backBtn2ActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomeScreen h = new HomeScreen();
        h.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    //Example of writing to a File

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        TeamInput = questionTf.getText();

        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        //Use a try statement
        try {
            outFile = new File("output.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);

            //create objects
            oStream.writeObject(qList);
            //write objects to the file
            JOptionPane.showMessageDialog(null, "Your selection has been saved !");
            //close stream
            oStream.close();
        } //catch the IOException
        catch (IOException e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    //Example of Reading a File
    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        //use a try statement
        try {
            inFile = new File("output.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);

            qList = (ArrayList<TeamSearch>) oStream.readObject();

            for (TeamSearch x : qList) {
                JOptionPane.showMessageDialog(null, "You picked: " + x.getTeamInput() + " to win the World Cup, good choice!");
            }

        } catch (IOException e) {
            System.out.print(e);
        } catch (ClassNotFoundException ex) {
            System.out.print(ex);
        }
    }//GEN-LAST:event_viewBtnActionPerformed


    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        TeamInput = questionTf.getText();

        //create a new Question object
        TeamSearch ts = new TeamSearch();

        //add contents of textfields to q
        ts.setTeamInput(TeamInput);

        //add q to array of Question objects
        qList.add(ts);
        //increase count to show that another object has been added to the array
        count++;
    }//GEN-LAST:event_addBtnActionPerformed

    //Deleting from File

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if (questionTf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "You must enter a team to delete");
        } else if (count == 0) {
            JOptionPane.showMessageDialog(null, "Sorry, there are no items to delete at this time");
        } else {
            TeamInput = questionTf.getText();

            for (int i = 0; i < qList.size(); i++) {
                if (qList.get(i).getTeamInput().equals(TeamInput)) {
                    qList.remove(i);
                    count = count - 1;
                    JOptionPane.showMessageDialog(null, "Deleted team at index " + i);
                    break;
                }
                if (i == count - 1) {
                    JOptionPane.showMessageDialog(null, "Sorry, that team could not be found");
                }
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WCFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WCFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WCFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WCFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WCFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn2;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel cupLbl;
    private javax.swing.JLabel date1;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel finalLbl;
    private javax.swing.JPanel fixture1;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel matchLbl;
    private javax.swing.JLabel questionLbl;
    private javax.swing.JTextField questionTf;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel taskbar;
    private javax.swing.JLabel v1;
    private javax.swing.JLabel venue1;
    private javax.swing.JButton viewBtn;
    private javax.swing.JLabel w61Lbl;
    private javax.swing.JLabel w62Lbl;
    // End of variables declaration//GEN-END:variables
}
